### ISSUE TITLE
Error: Tried to encode an invalid date.

### ISSUE THREAD

**Issue by gimdongwoo** [ParsePlatform/parse-server#1077]
For implementation related questions or technical support, please refer to the [stackoverflow](http://stackoverflow.com/questions/tagged/parse.com) community.

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [ v ] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [ v ] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [ v ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
local & heroku

#### Steps to reproduce
curl -X GET \
  -H "X-Parse-Application-Id: " \
  http://localhost:5000/parse/classes/Alarms
* On Parse.com is OK, but errors on Parse Server
* Exported Data from Parse.com : https://drive.google.com/file/d/0B13IpTDdfr3ONEtTeXBVOGs2SEU/view?usp=sharing

#### Logs/Trace
web.1  | Uncaught internal server error. [Error: Tried to encode an invalid date.] Error: Tried to encode an invalid date.
web.1  | es/parse-server/lib/transform.js:714:31)

**Comment by hramos** [comment]
Hi @gimdongwoo, the best way to illustrate an issue is with a failing test. Any chance you can pinpoint the specific object that causes Parse Server to respond with this error message?

**Comment by campers** [comment]
I'm getting the same with v2.1.6 error from a call to Parse.Query.lessThan()

My cloud code is
var birthdateTo = new Date()
birthdateTo.setFullYear(birthdateTo.getFullYear() - profile.ageFrom)
profileQuery.lessThan("birthdate", birthdateTo)

and the rest of my stack trace is:
parse-server-example/node_modules/parse-server/node_modules/parse/lib/node/encode.js:69:13)
parse-server-example/node_modules/parse-server/node_modules/parse/lib/node/encode.js:95:10)
parse-server-example/node_modules/parse-server/node_modules/parse/lib/node/ParseQuery.js:171:61)
parse-server-example/node_modules/parse-server/node_modules/parse/lib/node/ParseQuery.js:533:19)

**Comment by hramos** [comment]
Parse Cloud Code and parse-server Cloud Code are two different environments, and there are bound to be some small differences between the two.

We are closing this issue due to a lack of sufficient information. Note that we expect that some developers will need to update their Cloud Code when migrating to parse-server, and we are not considering minor differences between the two environments as actionable issues in parse-server.

Please refer to [this issue](https://github.com/ParsePlatform/parse-server/issues/1271) for an example of a great bug report.

You may use [Server Fault](https://serverfault.com/tags/parse) for questions about managing Parse Server.

For code-level and/or implementation-related questions or technical support, please refer to [Stack Overflow](http://stackoverflow.com/questions/tagged/parse.com).

**Comment by nodechefMatt** [comment]
This pull request should fix this issue
https://github.com/ParsePlatform/parse-server/pull/3389

**Comment by decider** [comment]
I found this issue to happen anytime we try to save a date with a UTC offset that starts with a +
