### ISSUE TITLE
Debug cloud code locally

### ISSUE THREAD

**Issue by meoz** [ParsePlatform/parse-server#1115]
More of a question than a bug. I've set up Parse Server on Heroku and wondered how I could run and debug cloud code locally ? Is there a guide somewhere explaining how to do this ?

**Comment by gfosco** [comment]
Run the project locally, instead of on heroku.  It's very easy.  Clone your repo from Heroku if you used the 1-click button, and then `npm install` and run it local.  I use mostly `console.log` debugging, but this looks like it will work as well: https://nodejs.org/api/debugger.html

I feel like we've failed somewhere in guidance, because I feel like running it local should always be the first step.

**Comment by gowridev** [comment]
If i setup my parse server in ibm bluemix? can i write my cloud code in bluemix (same server) or i need to have heroku account?
