### ISSUE TITLE
Client push is not supported. You can only use masterKey to send push notifications.

### ISSUE THREAD

**Issue by davimacedo** [ParsePlatform/parse-server#1123]
From https://github.com/ParsePlatform/parse-server/wiki/Push, "Client push is not supported. You can only use masterKey to send push notifications".

Is there any reason? Is a contribution about it welcome?

**Comment by gfosco** [comment]
It is not secure to allow clients to send push notifications directly, because then any one who has your app id can send/spam to your users.  It has been default-off and not recommended on Parse for a very long time.

The best way to solve this is to have the users call a cloud function, and send the push from there using the master key.  JS example code available here: https://github.com/ParsePlatform/parse-server/wiki/Push#4-send-push-notifications
