### ISSUE TITLE
GridStoreAdapter files location

### ISSUE THREAD

**Issue by davimacedo** [ParsePlatform/parse-server#1131]
Because of https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/Files/GridStoreAdapter.js#L66 when using nginx (or other) to proxy requests, you don't have enough control over the files location url.

My suggestion is to use like it currently is as a default behavior but add an optional parameter in the GridStoreAdapter to set the file location (instead of the default config.mount).

I would like to know if a contribution about it would be welcome.

**Comment by flovilmart** [comment]
@davimacedo would you set a publicServerURL, and use that as the base?

**Comment by davimacedo** [comment]
@flovilmart I will try today and revert to you. thanks.

**Comment by seijiakiyama** [comment]
@flovilmart @davimacedo the _publicServerURL_ didn't work here at [back{4}app](https://back4app.com).

We've tested through files being shown with "_http://_" (They're served under both HTTP and HTTPS protocols). But we needed it to be "_https://_" by default.
So, the problem was solved by adding the "_X-Forwarded-Proto_" header as "_https_" on _nginx_ and adding "_app.enable('trust proxy');_" to our express.
Then, _config.mount_ will receive the desired protocol on _req.protocol_.

That solved our problem, but we still think that there could be another way to do that, just like suggested on https://github.com/ParsePlatform/parse-server/issues/1131#issuecomment-199785174.
We're willing to contribute about it.

**Comment by justinmfischer** [comment]
We are also behind nginx on AWS. Is it also possible to implement a custom GridStoreAdapter and configure it while creating the server? Something like this...

var gridStoreAdapter = require('parse-server'). GridStoreAdapter;
var api = new ParseServer({
  ...
  filesAdapter: new gridStoreAdapter('http://my.mount.url'),
  ...
});

**Comment by flovilmart** [comment]
@seijiakiyama we're waiting on your contribution then!
