### ISSUE TITLE
Vote: Take down claims you can roll your own server til its ready

### ISSUE THREAD

**Issue by corbanb** [ParsePlatform/parse-server#1160]
This is not possible.
![screen shot 2016-03-23 at 9 58 15 am](https://cloud.githubusercontent.com/assets/140186/13991990/d6334940-f0df-11e5-8343-487b2888021b.png)

Currently there is 0 way to actually get a prod instance of the parse server live and working. I have been working for weeks to get parse sever up but there are way to many road blocks for it to actually work. The home page of parse.com claims this is doable but is far from the truth. I think Parse needs to do a better job of what it is claiming to the community and do a better job of communicating when this will actually be ready. 

**Major Issues: **
- No Password Reset  
- Inconsistencies with SDKs and REST API  
- No Documentation to migrate of background jobs
- Data exports not formatted for mongoimport without manual changes or large datasets

I'm sure there is an even larger list and you can read issues here around more topics. But with so many problems claiming this is even possible is BS and leading teams down lengthy paths to hit dead ends. I think Parse needs to figure out a better community message and a more clear path to reaching an actual 1.0 of the features needed to actually use parse in production. 

I hope the community and Parse feels this is a fair claim and can help clean this up until things are stable.

**Comment by btate** [comment]
I second this.  

Although I think I can add some insight into a couple of these. 

The database migration tool in the parse.com app settings page worked for our dev and UAT environments, although we haven't tried it in production yet.  We didn't try to do an export import. 

I thought the password reset was working as of 2.1.4 or 2.1.5.  We had it working using the custom pages, we haven't tested with the defaults.

We were able to get background jobs working using https://github.com/Automattic/kue and redis.  There is no documentation for it in parse-server but you can go through the kue documentation and it should point you in the right direction.  The biggest hurdle we ran into here was getting redis installed and running properly.  We have an amazon elastic beanstalk environment so we only wanted these background jobs running on the leader node.  I have an ebextensions file that installs redis if needed and starts it on the leader node.  The in our kue job definition we just check to see if redis is running  If you're in that environment and need the file let me know and I'll throw it up here. 

The inconsistencies with the SDKs and the REST API are still a thing as far as I've seen though and there seem to be random little things that don't work or are missing. 

Is there any kind of timeline for this being production ready?

**Comment by gfosco** [comment]
There are quite a few prod instances running on it, even though it's still really early..  It's only been 56 days since we announced it, and it is moving very quickly towards stability and parity with parse.com.

Your list of major issues are not major at all.  Password reset and all the email functionality has been in active development and is already working.  Inconsistencies are what we're trying to identify and fix... We can do some guidance / examples when it comes to background jobs, but it is incredibly easy to use a node script + cron... Data exports?  Use the migration tool.  The json exports were never intended for this and of course it would require a lot of manual intervention.  

Help us.  When you identify an inconsistency, let us know.  Repro steps, or some logs, or a full test case, whatever you're willing to do... but don't complain about how your brand new free software isn't perfect immediately.

I am closing this extremely unhelpful issue.

**Comment by otymartin** [comment]
@corbanb I understand your complaints relative to Parse.com but the team didn't have to do any of this. They could have just shut down and focused on building Facebook/Instagram or something. The engineering hours they put into building and managing this resource is more than you and I could afford in this lifetime.

Im struggling with small things here and there due to lack of knowledge of server side management but I gets better every day. Not to mention Parse-server is already way better than parse.com (liveQueries :100: ) and will only get infinitely better.

Patience...

**Comment by corbanb** [comment]
I am just asking that the claim its ready for production change. Its not true and is not ready. 

Parse needs to be more clear... and no its not easy. If it was I wouldn't be bothering about this.

**Comment by cchitsiang** [comment]
@btate definitely would like to know your solution to deploy redis to AWS Elastic Beanstalk. Would you mind to share? (Also looking at kue ;) but redis is my concern on stability in elastic beanstalk environment)

**Comment by flovilmart** [comment]
There are many strategies to run jobs with elastic beanstalk, I suggest you look at the worker tier, redis may not even be needed as you can uses SQS and the worker tier has an SQS consumer in it
