### ISSUE TITLE
Any way to create blank parse class

### ISSUE THREAD

**Issue by samarthagarwal** [ParsePlatform/parse-server#117]
Hi. I was wondering if there is a way to create blank Parse classes like we have on the Parse Dashboard. Thanks.

**Comment by christianmarth** [comment]
You can use the Create Object API to create a new object, if the class doesn't exist it will be created for you

https://parse.com/docs/rest/guide/#objects-creating-objects

**Comment by samarthagarwal** [comment]
What I am looking for is to create a class with no data in it.

**Comment by christianmarth** [comment]
This empty class will be populated with data in your application I assume so you can just use the client SDK to create the objects and if the class doesn't exist it will be created for you. From there you can perform CRUD operations on your new class, If you're looking for a dashboard you may want to follow Issue #3

**Comment by gfosco** [comment]
So, what was likely occurring on the Parse dashboard, is that we created the _SCHEMA entry for a new class, but it wasn't actually 'created' unless you saved an object.  I don't see any value in creating the collection empty here, but the dashboard will no doubt offer the same functionality, since it gets the collection list from the _SCHEMA.
