### ISSUE TITLE
response.success() does not return in beforeSave

### ISSUE THREAD

**Issue by jiawenzhang** [ParsePlatform/parse-server#1205]
```
Parse.Cloud.beforeSave("Item", function(request, response) {
  response.success();
  console.log("after response"); // this gets executed.
}
```

in parse.com, the beforeSave returns when response.success() is called, but in parse server, it does not. 
tested on parse server 2.2.2

**Comment by flovilmart** [comment]
yes it doesn't exit the current call stack. Is that a big problem for you?

**Comment by jiawenzhang** [comment]
How to achieve the same effect as Paser.com? just call return?

**Comment by flovilmart** [comment]
yes, call return response.success();

**Comment by peeinears** [comment]
Curious, what are the implications of running code after a `response.success()` in a beforeSave, if any, (other than that it's funky)?

**Comment by drew-gross** [comment]
The code will still execute, and you can still save object and etc. but the client will have already received the response. This can actually be useful in some cases, for example we use something like this when sending password reset emails.

**Comment by peeinears** [comment]
@drew-gross Ah, cool. Thanks. I want to send a Pusher event to clients notifying that an object was updated. Ideally I'd like send the event with info about which attributes changed so that the client only has to fetch the updates, but of course I only have that info in beforeSave. If I send the Pusher event *before* `response.success()` in beforeSave then there's a possible (though unlikely) race condition where the client receives the event and fetches the object, but the object hasn't been saved yet. Does that sound right? If I send the Pusher event *after* `response.success()` do I eliminate this race condition or does it still exist?

**Comment by drew-gross** [comment]
If you want to ensure that the object has been saved, you need to run your logic in `afterSave`.

**Comment by peeinears** [comment]
@drew-gross that's what I figured. I just found out about `request.original` in afterSave so I *can* actually get the changed attributes in afterSave. Is `request.original` documented anywhere?

**Comment by drew-gross** [comment]
Hmm I don't see any docs. Would you like to add some? Our docs are open source in the https://github.com/ParsePlatform/Docs repo

**Comment by peeinears** [comment]
@drew-gross okay, [in here?](https://github.com/ParsePlatform/Docs/blob/2ce5113fb3acb6969f9846061703f54ccd0f38bb/en/cloudcode/cloud-code.mdown#afterdelete-triggers)

Are [these docs](https://parse.com/docs/js/api/classes/Parse.Cloud.AfterSaveRequest.html) no longer relevant for parse-server?

**Comment by drew-gross** [comment]
Yep, thats right. The JS SDK docs are still relevant I think, but maybe you could check on the JS SDK repo if you want to delete them.
