### ISSUE TITLE
how to deploy send grid on heroku

### ISSUE THREAD

**Issue by kukkadapukarhtik** [ParsePlatform/parse-server#1274]
Here is my cloud code on parse,i want to deploy on heroku
Parse.Cloud.define('sendEmail', function(request, response) {
var toUser=request.params.toUser;
var subject = request.params.subject;
var body = request.params.msgBody; 
    var sendgrid = require('sendgrid');
    sendgrid.initialize("username", "password");
           
    sendgrid.sendEmail({
        to: toUser,
        from: 'no-reply@myapp.com',
        subject: subject,
        html: body
    }, {
    success: function(httpResponse) {
        console.log(httpResponse);
        response.success('Email sent!');
    },
    error: function(httpResponse) {
        console.error(httpResponse);
        response.error('Uh oh, something went wrong');
    }
    });
});

this is my cloud function ,but it is not working it says following eroor
[Error]: {"code":1,"message":"Internal server error."} (Code: 1, Version: 1.12.0)

**Comment by drew-gross** [comment]
If there is an internal server error, there should be more info logged by the server. Can you post those logs?

**Comment by kukkadapukarhtik** [comment]
how to deploy send grid on heroku server

**Comment by hramos** [comment]
We are closing this issue due to a lack of sufficient information. 

Please refer to [this issue](https://github.com/ParsePlatform/parse-server/issues/1271) for an example of a great bug report.

Make sure these boxes are checked before submitting another issue -- thanks for reporting issues back to Parse Server!

- [ ] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [ ] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

For implementation related questions or technical support, please refer to the [Stack Overflow](http://stackoverflow.com/questions/tagged/parse.com) and [Server Fault](https://serverfault.com/tags/parse) communities.

**Comment by kukkadapukarhtik** [comment]
here is my log
![screen shot 2016-04-06 at 1 33 39 am](https://cloud.githubusercontent.com/assets/12559796/14296466/f4aec7c4-fb97-11e5-80e0-49d4a069ece4.png)

**Comment by hramos** [comment]
The error says that sendgrid is not defined. Check and make sure you have installed the sendgrid npm correctly. This is a general Node.js programming question, and is not something we're providing support for in this repo's issues.
