### ISSUE TITLE
Parse is Bandwidth throttling non migrated apps from April 28th - But how do I add jobs & cloudcode to my migrated db?

### ISSUE THREAD

**Issue by hjgabrielsen** [ParsePlatform/parse-server#1356]
Do I have to code everything from scratch myself?

As you all know Parse is Bandwidth throttling non migrated apps from April 28th - But how do I add jobs & cloudcode to my migrated db?

Does anyone have a working solution to this, 

Right now I have :

DB
Cloudcode 
Jobs running every 15 minutes.. 

Thats it..

**Comment by jon1010hill** [comment]
Hi

As long as you have migrated your database you shouldn't be throttled. You have some more time to move the application.

> If you do not migrate your database by April 28, we will assume you do not consider the app's migration to be a high priority. Traffic to your app may be de-prioritized as we shift our focus to serving production apps that are being migrated according to our recommended schedule."

**Comment by hjgabrielsen** [comment]
Yeah, i know,-  but can I control my remote DB from parse panel? w/ cloudcode etc.. ?

**Comment by tanmays** [comment]
Also you should consider beginning to migrate as soon as you can. Follow the [migration tutorial](https://github.com/ParsePlatform/parse-server/wiki/Migrating-an-Existing-Parse-App) to get DB and CloudCode working on your self hosted parse server.

As for jobs, they are not supported by `parse-server` yet because of the sheer number of options available. A particular solution might work better on a particular hosting service, so its up to the developer to choose the best one that fits well with his setup. 

I've been using [Kue](https://github.com/Automattic/kue) and [Cron-Cluster](https://github.com/iGLOO-be/cron-cluster) module to add in background jobs and cron support, you may want to check that.

**Comment by flovilmart** [comment]
@hjgabrielsen the parse.com dashboard will continue working with the migrated database, so you don't have to disrupt your workflow, the jobs, cloud code etc... will all keep working correctly.

**Comment by iOSassou** [comment]
Interesting info. I thought you had to use the open source dashboard as soon as you've migrated your database. So as long as we're still hitting api.parse.com (and not our own Parse Server instance), the data shown in Parse.com dashboard will sync perfectly, correct?

**Comment by flovilmart** [comment]
That's right!
