### ISSUE TITLE
Removing all records doesn't affect DB snapshot

### ISSUE THREAD

**Issue by michalhartwich** [ParsePlatform/parse-server#1376]
Hi,
I've removed all records in Parse Dashborad (in dashboard.parse.com) through Edit -> Delete All Rows, but records are still present  in DB dump and during migration to external MongoDB instance. DB size in Analitics in not affected. What should I do to destroy permanently?

Migrating other apps went without any issues.

**Comment by zleman1593** [comment]
Not a solution, but related. I noticed when I delete a column in Parse Dashboard the fields corresponding to that row are still present in all the Objects exported during migration.

**Comment by michalhartwich** [comment]
Few days ago I've migrated test environment of this app and I removed content of particular table and DB was reduced immediately. Removed data weren't migrated.

**Comment by rad3ks** [comment]
AFAIK migration is being done from some sort of DB snapshot. I guess there was no new snapshot after the changes were made. 

The problem @michalhartwich described is that we have really huge table where older rows are not needed, so we decided to delete them all (we could do this), so the migration will be quick. Currently, migration tool tries to migrate everything from before the deletion. It worked for us in other app, but not on this one.

It would be great if we could trigger some mechanism on the server that will make new snapshot, so we can migrate tiny DB instead of few GBs.

**Comment by flovilmart** [comment]
Please report that issue to parse.com directly using http://parse.com/help as this is not related to parse-server
