### ISSUE TITLE
External File Adapter Dependencies

### ISSUE THREAD

**Issue by mamaso** [ParsePlatform/parse-server#1434]
Hey, noticed that the GCS file adapter was moved to devDependencies in this commit https://github.com/ParsePlatform/parse-server/commit/1eb2a87f9f0b5328ebeaaf0eb2f82b86150f2b13

I like the opt-in approach to these dependencies for production parse servers, any similar plans for S3 / ParseFS adapters?

**Comment by drew-gross** [comment]
The reason for that one is because the one of the transitive dependencies needed to compile native code and required more than 1GB of RAM to do so, causing install failures on AWS micro instances. I agree that it's a better model to have the dependencies be opt-in, but thats also a breaking change and I'm not sure if the benefit of the breaking change justifies the cost to everyone else, like it did with the GCS adapter.

**Comment by mamaso** [comment]
Makes sense, not worth the pain of the breaking change unless if there are extenuating circumstances like native module failures.  Thanks
