### ISSUE TITLE
Security of values

### ISSUE THREAD

**Issue by chderen** [ParsePlatform/parse-server#1535]
Hi,
Looks like that end user can insert bad values without basic security check.

For Example
set value of key to javascript code.
there is no change to html Entities for special chars like < atc.
so the user can insert < script > with unsecured actions.

Thanks

**Comment by gfosco** [comment]
I don't think that sanitization belongs to the server, because what if you wanted to insert arbitrary html/javascript in a text column?

You can implement this validation/modification in beforeSave triggers, you definitely don't want to take user-submitted content and execute it without sanitizing it yourself.
