### ISSUE TITLE
whereKey: notEqualTo

### ISSUE THREAD

**Issue by aliasad106** [ParsePlatform/parse-server#1585]
Parse query with whereKey: notEqualTo does not work

When I try to filter the users which are friend It does return me correctly like

`[query whereKey:@"friends" equalTo:[PFUser currentUser]];`

However when I try to query all those who are NOT friends like below

`[query whereKey:@"friend" notEqualTo:[PFUser currentUser]];`

It just returns me all users from _User class and does not filter based on the relation.

Check out [this issue](https://github.com/ParsePlatform/parse-server/issues/1271) for an ideal bug report. The closer your issue report is to that one, the more likely we are to be able to help, and the more likely we will be to fix the issue quickly!

For implementation related questions or technical support, please refer to the [Stack Overflow](http://stackoverflow.com/questions/tagged/parse.com) and [Server Fault](https://serverfault.com/tags/parse) communities.

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

**Comment by hramos** [comment]
We are closing this issue due to a lack of sufficient information. We can reopen once the issue is clearer.

Please refer to [this issue](https://github.com/ParsePlatform/parse-server/issues/1271) for an example of a great bug report.

You may use [Server Fault](https://serverfault.com/tags/parse) for questions about managing Parse Server.

For code-level and/or implementation-related questions or technical support, please refer to [Stack Overflow](http://stackoverflow.com/questions/tagged/parse.com).
