### ISSUE TITLE
Empty authData in user search request

### ISSUE THREAD

**Issue by dbezborodov** [ParsePlatform/parse-server#1703]
parse-server is not returning authData field in user search requests. Using v.2.2.7 POST request to _User class:
{"where":{"objectId":"xxxxxxx"},"limit":200,"order":"-createdAt,-createdAt","_method":"GET"}

returns something like:
{"results":[{"objectId":"xxxxxxx","createdAt":"2015-12-03T08:41:50.980Z","updatedAt":"2016-05-03T13:09:06.697Z","username":"xxxxxxxxxxx"}]}

but original parse API also returns authData:
{"results":[{"authData":{"facebook":{"access_token":"<access_token>","expiration_date":"2016-07-02T07:16:46.815Z","id":"<id>"}},"createdAt":"2015-12-03T08:41:50.980Z","username":"xxxxxxxxxxx"}]}

Both parse-server and parse API use the same Mongo database.
This issue makes parse-dashboard always showing authData as "undefined".

**Comment by steven-supersolid** [comment]
I think this is a duplicate of #1568
If so, it has been fixed in the next release

**Comment by dbezborodov** [comment]
yes, exactly. 
Thanks.

**Comment by robtaireeo** [comment]
@dbezborodov @steven-supersolid is there a timeline for the next release? (sorry, dont know where else to ask)

**Comment by steven-supersolid** [comment]
I can't imagine it will be too much longer due to the last release date being some time ago - would be really useful to know the release strategy going forward.

I highly recommend you fork the repo though. You can then make a pre-2.2.8 branch, build and commit the lib folder, then use your fork/branch as an git npm dependency. This will enable you to apply other fixes as required.
