### ISSUE TITLE
Cloud Code can not fetch data in updated parse object 

### ISSUE THREAD

**Issue by Wolke** [ParsePlatform/parse-server#1739]
as title , have to reboot server

**Comment by bohemima** [comment]
Code to reproduce?

**Comment by hramos** [comment]
We are closing this issue due to a lack of sufficient information. We can reopen this issue once you provide more details.

Please refer to [this issue](https://github.com/ParsePlatform/parse-server/issues/1271) for an example of a great bug report.

You may use [Server Fault](https://serverfault.com/tags/parse) for questions about managing Parse Server.

For code-level and/or implementation-related questions or technical support, please refer to [Stack Overflow](http://stackoverflow.com/questions/tagged/parse.com).
