### ISSUE TITLE
facebook registration

### ISSUE THREAD

**Issue by gotitapp** [ParsePlatform/parse-server#1745]
we have a problem with users that register to the app through facebook. Thier user information is not save in Parse. we have several thousands of new users every day and we need your urgent attention. thanks

**Comment by drew-gross** [comment]
Is thi with Parse Server or api.parse.com?

**Comment by hramos** [comment]
I understand this app is not using Parse Server. @gotitapp please file a bug via https://parse.com/help#report if this is specific to hosted Parse.com and/or Parse.com Cloud Code.

If this bug is specific to Parse Server, please provide more details. The placeholder text provided when you open a new issue has guidance on what kind of info we're looking for.
