### ISSUE TITLE
Unable to connect to the Parse API after implement ssl (HTTPS) 

### ISSUE THREAD

**Issue by w3care25** [ParsePlatform/parse-server#1845]
I am using self hosted parse-server and not able to use cloud functions since I have enabled HTTPS, if I revert it back to HTTP it works as expected.

Also he problem is only with those cloud function which have Parse.Query, if i create a function simply return "Hello" as response it works on both HTTP and HTTPS.

I am getting following error message when run a cloud function which have Parse.Query code.

**{
    "code": 141,
    "error": "XMLHttpRequest failed: \"Unable to connect to the Parse API\"--100"
}**  

can anyone tell me how can I fix this?

**Comment by bohemima** [comment]
Did you also change the serverURL setting to match the new address?

**Comment by w3care25** [comment]
yes I have changed serverURL to https

**Comment by thamer898** [comment]
yes i have the same problem my app work's only on http

**Comment by brocoli** [comment]
I'm having the same problem. After enabling SSL, clients can't communicate with the Parse Server anymore. The Parse Dashboard can't connect either, whether I configure it to use the public https endpoint, or "http://localhost/parse" or even "http://localhost:1337/parse".

Also, if I ssh into the instance that's running the parse server and the dashboard, and I try to curl our public endpoint with ssh, it works perfectly.

This seems to be a bug in the Parse JS SDK. The common thing between the Parse Dashboard and the clients is that both use it.

**Comment by thamer898** [comment]
Hello

@drew-gross kindly advice ?


Regards

**Comment by drew-gross** [comment]
This sounds like an SSL setup issue that might be better suited to Server Fault. There are definitely people out there using Parse Server and Parse Dashboard over SSL, so I don't think it's a bug.

**Comment by thamer898** [comment]
Hello

@brocoli @andrew8712 can you please ask about the ssl setup for parse server in Server fault and get the required details for that based on @drew-gross advice ? 


Regards

**Comment by DanGTZ** [comment]
Hello, I have the exact same issue as @w3care25 and can't figure out what is our setup error :
- My parseServerUrl is configured to https://www.my-domain.com:443/parse
- All api calls from the outside of the server work perfect. For example I can send a GET REST API on https://www.my-domain.com:443/parse/classes/MyClass/id and this works. Also simple calls from the javascript sdk configured to the same https url work.
- But any call from the inside of the server (inner Cloud Function query for example) fails with this error : XMLHttpRequest failed: \"Unable to connect to the Parse API\"

@drew-gross You suggested that this is a SSL setup issue, but it seems that this is not the case, and that the problem comes from the parse-server not being able to access securely an url that is accessible successfully from the outside.

**Comment by flovilmart** [comment]
How do you configure SSL? nginx? apache? node.js? In all of those cases, you may wanna set `publicServerURL` to the https and `serverURL` to the http. Loopback for cloud code should go thought http to avoid the ssl overhead. 

In all these scenarios, you need 2 configuration, 1 configuration for the HTTPS another for the HTTP. Please refer to node, nginx or apache configuration. 


For node: https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener and https://nodejs.org/api/http.html#http_http_createserver_requestlistener

For nginx: [Reverse proxying](https://www.nginx.com/resources/admin-guide/reverse-proxy/) and [SSL](http://serverfault.com/questions/583374/configure-nginx-as-reverse-proxy-with-upstream-ssl) (note that in that example, you should use an http upstream, using the 1337 port over HTTP)

For apache: https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension

> My parseServerUrl is configured to https://www.my-domain.com:443/parse

You should strip 443 as https would automatically reach that port
