### ISSUE TITLE
Issue streaming video after downloading from Parse-Server

### ISSUE THREAD

**Issue by Williambeuil** [ParsePlatform/parse-server#1973]
### Issue Description

It seems that I can't stream my videos once I downloaded them from Parse backend. However I know that the videos are working well as you can play it from Chrome but not from Safari ( I don't know why ...).

My code to play the video on the AVPlayer is also right since I test it for multiple NSUrl from local database.

Several posts about it confirm that there is a problem going on but no one has an answer.

[http://stackoverflow.com/questions/35235340/ios-cant-stream-video-from-parse-backend](url)

[http://stackoverflow.com/questions/37016487/cant-stream-video-pffile-from-parse-server](url)

I'm using Heroku with mLab.

Thanks in advance if someone can help me.

**Comment by hramos** [comment]
We are closing this issue due to a lack of sufficient information. 

Please refer to [this issue](https://github.com/ParsePlatform/parse-server/issues/1271) for an example of a great bug report.

You may use [Server Fault](https://serverfault.com/tags/parse) for questions about managing Parse Server.

For code-level and/or implementation-related questions or technical support, please refer to [Stack Overflow](http://stackoverflow.com/questions/tagged/parse.com).

**Comment by indiandragon** [comment]
@Williambeuil Were you able to address this issue. As you say, there have been other cases reporting the same i.e  parseserver+heroku+mlab doesn't stream audio/video files (mp4) in safari/iOS. Both Parse/Heroku staff close this issue without further investigation, I will check with mLab staff as it is a paid subscription.

**Comment by indiandragon** [comment]
[Solved] The solution is given by @Bragegs here - https://github.com/ParsePlatform/parse-server/issues/1440#issuecomment-212815625 . In short, parse-server doesn't seem to be supporting streaming of audio/video and @Bragegs code enables it. I hope it get's PR and parse team looks into it.
