### ISSUE TITLE
Multiple push Notification

### ISSUE THREAD

**Issue by MattiaConfalonieri** [ParsePlatform/parse-server#2059]
From a couple day on android, if i delete and reinstall the app i receive multiple push... i run the last version of parse, until two days ago no problem... what's change?

**Comment by hramos** [comment]
We are closing this issue due to a lack of sufficient information. 

Please refer to [this issue](https://github.com/ParsePlatform/parse-server/issues/1271) for an example of a great bug report.

You may use [Server Fault](https://serverfault.com/tags/parse) for questions about managing Parse Server.

For code-level and/or implementation-related questions or technical support, please refer to [Stack Overflow](http://stackoverflow.com/questions/tagged/parse.com).
