### ISSUE TITLE
Sometimes Twitter login is failed

### ISSUE THREAD

**Issue by edwardyue** [ParsePlatform/parse-server#2101]
Hi Team,

Sometimes I could not login as Twitter. However after wait for a while, I could login back successfully.

Normally , i would see following error message when login is not successful.

[Error]: Twitter auth is invalid for this user. (Code: 101, Version: 1.12.0)

Could you please advise?

Thanks and Regards,
Edward

**Comment by flovilmart** [comment]
Can you provide more details regarding the login failure running the server with VERBOSE=1?

**Comment by hramos** [comment]
We are closing this issue due to a lack of sufficient information. 

Please refer to [this issue](https://github.com/ParsePlatform/parse-server/issues/1271) for an example of a great bug report.

You may use [Server Fault](https://serverfault.com/tags/parse) for questions about managing Parse Server.

For code-level and/or implementation-related questions or technical support, please refer to [Stack Overflow](http://stackoverflow.com/questions/tagged/parse.com).
