### ISSUE TITLE
Cloned parse server return empty when I use condition with $gte, $eq and etc. 

### ISSUE THREAD

**Issue by jiangylking** [ParsePlatform/parse-server#2116]
New parse server return empty:
curl -X GET -H "X-Parse-Application-Id: xxxxxxxxxxxxxxxxxxx" -H "X-Parse-REST-API-Key: xxxxxxxxxxxxxxxxx" -G --data-urlencode 'where={"createdAt":{"$gte":"2015-12-14T06:58:02.196Z"}}' http://54.223.98.70/1/classes/Group
{"results":[]}

Old parse server return some records:
curl -X GET -H "X-Parse-Application-Id: xxxxxxxxxxxxxxxxxxx" -H "X-Parse-REST-API-Key: xxxxxxxxxxxxxxxxx" -G --data-urlencode 'where={"createdAt":{"$gte":"2015-11-09T01:36:05.570Z"}}' https://api.parse.com/1/classes/Group

These data are clone from parse.com, where I make wrong?  

Thanks
Yanlong

**Comment by hramos** [comment]
We are closing this issue due to a lack of sufficient information. 

Please refer to [this issue](https://github.com/ParsePlatform/parse-server/issues/1271) for an example of a great bug report.

You may use [Server Fault](https://serverfault.com/tags/parse) for questions about managing Parse Server.

For code-level and/or implementation-related questions or technical support, please refer to [Stack Overflow](http://stackoverflow.com/questions/tagged/parse.com).
