### ISSUE TITLE
Inconsistencies with live query

### ISSUE THREAD

**Issue by kajensen** [ParsePlatform/parse-server#2123]
I've noticed some inconsistencies with the live query implementation and am curious if anyone has any insight. For a node js web app with client side javascript subscriptions, usually (haven't really noticed any tangible reproduction steps as to why it doesn't work- but usually occurs after numerous (100+) subscription events with multiple objects) pointer columns are included with their data so no additional calls/local cacheing is necessary. With the iOS live query client nothing is ever included- regardless of the query. Why is this? I noticed #1686 but I'm certain that it (usually) works already with a JS client.

It would be awesome if includes were fully supported in live queries!

**Comment by hramos** [comment]
Hey @kajensen, it seems like several issues are being discussed here. It would be helpful to split this into individual, actionable issues.

Given that the behavior changes across SDK clients, it may be possible that these are SDK issues rather than Parse Server issues.

If you are able to reproduce the issue where a client side JavaScript SDK subscription does not include a pointer, please open a new issue against the [JavaScript SDK](https://github.com/ParsePlatform/Parse-SDK-JS) with detailed repro steps.

For iOS, please open a new issue against the [iOS SDK](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX) with additional details such as the iOS SDK version and Parse Server version the issue was reproduced with.
