### ISSUE TITLE
Query returns empty result is some devices, not in others

### ISSUE THREAD

**Issue by xissburg** [ParsePlatform/parse-server#2180]
We're getting this issue intermittently with a few specific classes, simple queries. The results are returned properly in most devices and in some we're getting an empty result. I can see the empty result being returned in the server logs as well, there are no errors. Queries are made using the same user in all devices. This makes no sense, I have no idea. I have changed CLPs and ACLs to public read/write and nothing changed.

I am just leaving this here. I don't think I will be able to reproduce it in a small sample project.

We're having too many little non-sense issues with Parse and we have nobody to rely on to help handle such urgent issues which make the product unusable. Thus we have decided to migrate to something else for now.

**Comment by hramos** [comment]
We are closing this issue due to a lack of sufficient information. 

Please refer to [this issue](https://github.com/ParsePlatform/parse-server/issues/1271) for an example of a great bug report.

You may use [Server Fault](https://serverfault.com/tags/parse) for questions about managing Parse Server.

For code-level and/or implementation-related questions or technical support, please refer to [Stack Overflow](http://stackoverflow.com/questions/tagged/parse.com).
