### ISSUE TITLE
Getting error when Try to sent push from cloud code

### ISSUE THREAD

**Issue by mkaya93** [ParsePlatform/parse-server#2228]
I'm trying to sent push notifications to multiple users from cloud code but I'm getting error. 

```
var query = new Parse.Query(Parse.Installation);
         var user = [Parse.User];
         user = results
        console.log(user);
        query.equalTo('users', user);
        Parse.Push.send(
        {   
            where: query,
            data: 
            {
            alert: groupName + " grubuna yeni bons geldi.",
            isJSONPush: 'true',
            badge: 'increment',
            sound: 'default'
            }
        },{ useMasterKey: true }, 
        {
            success: function() {
            console.log('##### PUSH OK');
            },
            error: function(error) {
            console.log('##### PUSH ERROR' + error.message);
            }
        });


```

and this is console log.

```
[ ParseUser { _objCount: 11, className: '_User', id: 'FrryTbQGGo' },
  ParseUser { _objCount: 12, className: '_User', id: 'o32fxqTfTs' } ]
info: warning: error while sending push code=107, message=You cannot use [object Object],[object Object] as a query parameter.

```

**Comment by sudochownrwhoami** [comment]
> var user = [Parse.User]
> user = results
> console.log(user);
> query.equalTo('users', user);

You are assigning the value of 'results' to 'user' and from your log it looks 'results' is an array.
Then you're creating a query that specifies that 'users' must be equal to an array.

try something like,

> var users = results
> query.containedIn('users', users);

or

> var users = results
> query.equalTo('users', users[0]);

Give those a shot and see which one works the way you want it to

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
