### ISSUE TITLE
Parse Server on Drupal

### ISSUE THREAD

**Issue by JustinDMoore** [ParsePlatform/parse-server#2273]
Parse server is currently running on Heroku for our production iOS app. We are possibly looking at integrating it with our website, which is hosted on Drupal. 

Has anyone gotten parse server to run on Drupal? Is there a guide available?

**Comment by bohemima** [comment]
Drupal is a CMS written in PHP, do they have some kind of dedicated hosting now? If the hosting service where you have the Drupal instance up and running supports Node and MongoDB, sure, you can but I wouldn't. Keep them separated.

**Comment by ranhsd** [comment]
What you can probably do is to consume your parse server api's from your website using the Parse PHP SDK [https://parse.com/docs](url)

**Comment by gateway** [comment]
I used drupal and have written several modules to pull in data from parse... I'm just not sure exactly what your question is .. Drupal = PHP, parse Node.js/Express completely different.

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
