### ISSUE TITLE
PFFile profile image name won't save correctly, Missing PFFiles after migration. Parse Dashboard Naming bug

### ISSUE THREAD

**Issue by alexrmacleod** [ParsePlatform/parse-server#2282]
I save a user with a profile picture like so 

`

    let imageData: NSData = UIImagePNGRepresentation(profilePictureImageView.image!)!
            let profilePicture: PFFile = PFFile(name: "profile.png", data: imageData)!
            self.user.profilePicture = profilePicture
        
            self.user.saveInBackground().continueWithBlock({
                (task: BFTask!) -> AnyObject! in
                if task.completed {

`

But in the parse dashboard it shows up like the below screenshot, as you can see 2 user profile_pictures are named 'ile.png' INCORRECT.... The last user_name and profile_picture was from before I migrated to parse server. Strangely all the users created before the migration to parse server, their profile_pictures are missing. And the new profile pictures aren't named correctly. 

![screen shot 2016-07-15 at 12 30 14 am](https://cloud.githubusercontent.com/assets/7895493/16847475/cd13bc6c-4a23-11e6-803f-462453d447e6.png)
 

Also on my model when I get the image from newly created users post the parse server migration the below does work. So maybe theres a PFFile naming bug on the new parse dashboard. 

`

          var profilePicture: PFFile {
            get {
              return objectForKey("profile_picture") as! PFFile
            }
            
            set {
              setObject(newValue, forKey: "profile_picture")
            }
          }

`

**Comment by hramos** [comment]
Can you check what the actual response is when using the REST API? If the response contains everything you'd expect, it would likely point to an issue with the [parse-dashboard](https://github.com/pareplatform/parse-dashboard), which has its own separate repository and issue tracker.

If the issue is not in Parse Dashboard, you'll want to determine if this is an issue in the iOS SDK or in Parse Server.

Feel free to reopen the issue once you've dug deeper into this. Make sure to refer to the new issue template which has all the fields necessary to open a bug report against Parse Server.
