### ISSUE TITLE
Live query cloud code

### ISSUE THREAD

**Issue by greggmojica** [ParsePlatform/parse-server#2306]
I have a web app which uses ACLs and cloud code to make queries (as default fetching is disabled by CLPs).  However, how would I create a live query subscription using cloud code to override ACLs? Code examples would be highly appreciated!!

**Comment by greggmojica** [comment]
Hey @flovilmart any chance you can offer your opinion here? You've been really helpful! Thanks

**Comment by vutana1** [comment]
Hi. Have you found a solution? Thanks.

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
