### ISSUE TITLE
Parse server is not responding after sign-up.[We are forced to restart it again].

### ISSUE THREAD

**Issue by SrinathReddyKolanu** [ParsePlatform/parse-server#2343]
Please resolve this issue,

We are using parse object to singup from our application. After repeating the same for 5 times continuously the parse serve is not responding and we are forcing parse server to restart after which it works as expected. Can you please guide us in this.

Do parse having any issue with signup or any problem with our code.

**Comment by bohemima** [comment]
Please follow the https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md when creating issues.

**Comment by hramos** [comment]
We are closing this issue due to a lack of sufficient information. 

Please refer to [this issue](https://github.com/ParsePlatform/parse-server/issues/1271) for an example of a great bug report.

You may use [Server Fault](https://serverfault.com/tags/parse) for questions about managing Parse Server.

For code-level and/or implementation-related questions or technical support, please refer to [Stack Overflow](http://stackoverflow.com/questions/tagged/parse.com).
