### ISSUE TITLE
Import data with mongoimport causes error "101 object not found" while updating my data

### ISSUE THREAD

**Issue by alex290796** [ParsePlatform/parse-server#2358]
my setup

local server on windows server 2012 r2 with mongodb 3.0 parse-server 2.2.7

Steps to reproduce

I launch a mongoimport.exe --db dev -u myuser -p mypass -c mycollection --type csv --headerLine --file file/path.csv
it imports the file with success, but when i try to modify an object i get an error 101 object not found (in Xcode, in rest api and in dashboard). Also if I try to filter by an objectId it found nothing

p.s I noticed that when I mongoimport it make a objectId with more than 10 characters.

Sorry if i wrong something i'm new here.

**Comment by ManuelLuRa** [comment]
Hi alex290796!

I have got your same issue. I'm researching about it and I think that it is due to user auth. I'm playing importing data and creating new entries.
I can read all imported data, but I can't update or modify it (from parse dashboard and android client have the same issue). However, if I create new entries, I can manage them without any problem!

I'm importing data to mongodb with the same user than parse server use, so I don't know what is the issue. 

I have found a workaround that maybe runs, but I don't try it. I have read that you can give read/write access to any user of a database in mongodb. You are breaking security with this, but maybe can be valid as a temporal solution.

Can anyone help us? Thank you so much!

**Comment by ManuelLuRa** [comment]
Hi again Alex!
I have solve the issue! The problem is when you importing data. Mongoimport does not use the same format that parse when creates "_id" field. If you see at any collection at mongo, you can see:

A entry imported from mongoimport:
{"_id":objectId(""),...}

A entry created from parse:
{"_id":"",...}

In my case, I didn't specify at .csv file a _id field, so mongoimport create it with this format. 

I have made a workaround that works for me in an easy way. 

1. I export the collection with json format. 
2. Open the json. Here you can see that all "_id" fields are declared as:
"_id":oid("")
3. Use "sed" tool to delete this wrong format and set it as "_id":""
4. Drop the collection at mongo in order to be replaced for the new one
5. Now, import fixed collection from json file.

This proccedure works for me! I know that it is a little bit archaic, but at least runs!

**Comment by hramos** [comment]
I think this report needs more information. Can you update your original post and make sure it provides all the information listed in the new issue template? Ping me once the information is there and we can reopen the issue.
