### ISSUE TITLE
Unable to send pushes via REST api when migrating from Parse to Nodechef

### ISSUE THREAD

**Issue by Francesca85** [ParsePlatform/parse-server#2496]
Hi all,
we are migrating our apps to Nodechef parse server with DBs hosted on Object Rocket.
While we are able to send pushes via Nodechef dashboard, we are unable to send pushes via REST api as we currently do with Parse.

### Steps to reproduce

This is the request sent from Nodechef dashboard:

POST /parse/push HTTP/1.1
Host: test-appname-1067.nodechef.com
Connection: keep-alive
Content-Length: 446
Origin: https://dashboard.nodechef.com
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Mobile Safari/537.36
Content-Type: text/plain
Accept: /
Referer: https://dashboard.nodechef.com/apps/test-appname/push/new
Accept-Encoding: gzip, deflate, br
Accept-Language: it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4

{"where":{"deviceType":{"$in":["ios"]}},"data":{"alert":"Text of the alert","category":"category of the alert","title":"Title of the alert","u":"2b30Yuh"},"_ApplicationId":"applicationid","_ClientVersion":"js1.6.14","_MasterKey":"masterkey","_InstallationId":"56205783-4f18-7427-919a-6e03ed80443a"}

This is the request we are trying to send:

curl -X POST \
  -H "X-Parse-Application-Id: applicationid" \
  -H "X-Parse-Master-Key: masterkey" \
  -H "Content-Type: application/json" \
  -d '{
 "where": {
  "deviceType":{"$in":["ios"]}
 },
 "data": "{\"alert\":\"Text of the alert\", \"category\": \"category of the alert\", \"title\": \"Title of the alert\", \"u\": \"2b30Yuh\"}"
}' \
https://test-appname-1067.nodechef.com/parse/push

We get no error (result:true) when trying this curl but no push is sent at all

We noticed several differences between the two requests so we tried to reproduce the same request sent via dashboard and still we were not able to send anything:
- we changed the content type in the header
- we specified the various keys in the body instead of the header
- we specified that "installation id" we have no clue of what is it

Already opened an issue to Nodechef, they couldn't help and suggested to post the issue here.

Thank you in advance for any help

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.

**Comment by Francesca85** [comment]
This is the link to the question on stackoverflow:
http://stackoverflow.com/questions/38897455/cant-send-push-notifications-via-rest-api-when-migrating-from-parse-to-nodechef
