### ISSUE TITLE
usage of API tokens

### ISSUE THREAD

**Issue by matthiasbaldi** [ParsePlatform/parse-server#2507]
Is it possible to generate API tokens for devices or users?
This would be great for IoT devices without a login form.
In your documentation I din't saw any information about that. Is a feature like that implemented or is it possible that this feature will implemented in the next time?

Thanks.

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.

You may also look into the source code for the embedded Parse SDKs for IoT.
