### ISSUE TITLE
Streaming Video files hosted on Google Cloud Storage

### ISSUE THREAD

**Issue by otymartin** [ParsePlatform/parse-server#2530]
@flovilmart @nlutsenko 

`Question`
My app is hosted on Google App Engine and I want to use Google Cloud Storage to host video files which I will stream to my iOS client. Previously people had trouble using self-hosted parse-server to stream videos. I'm wondering if theres any technical barriers preventing this right now

There was **[this hack](https://notehub.org/8ncql)**  by @Bragegs previously referenced however I haven't tried it.

#692 #1698 #1973

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
