### ISSUE TITLE
Can Push Notification use MQTT for sending messages

### ISSUE THREAD

**Issue by Sharathmk99** [ParsePlatform/parse-server#2540]
Hi,

I need to send push notification without GCM/APN, so decided to use MQTT for sending push notification.
Is any one aware of ow to use MQTT, if not please direct me how to develop this feature with Parse as core.

Thanks
Sharath

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.

**Comment by QWIlson2015** [comment]
HI @Sharathmk99 ,

yes you can, but only for android. You have to use a service working in background in your app. Instead for iOS you need a push notification to wake up your app if it's in background or closed. Once it's visible you can use mqtt to receive or send your messages.
