### ISSUE TITLE
Is the migration Seamless when I already had a lived database?

### ISSUE THREAD

**Issue by kenglou** [ParsePlatform/parse-server#255]
As titled. I already had 1 game on the Parse and around 700k users count with some other tables. I wish to know that If i want to move the Parse to AWS or some other solutions, will the database be seamless transferred? or will it has a downtime? I'm doing Android and iOS games, so i need some preparation on the downtime. Final question, will i need to re-upload another APK/IPA if I hosted the server after 28th Jan 2017? Parse is closing down after that date, is it including the Parse server or only the database Server?

Thank you.

**Comment by natanrolnik** [comment]
@kenglou i suggest you to read the migration guide, it answers your questions: 
The migration tool will handle the data while you do the migration, so there is no need to worry about downtime. 
And you will need to upload a new ipa/apk, so that in January 2017 all your users point to the new parse server (that you will need to deploy). 
Hope it helped you.

**Comment by kenglou** [comment]
@natanrolnik thanks, I already read the guide but that seems a bit confused for me. Now I'm glad that you can provide a straight forward question.

Just to clarify, is that means on 28 January 2017, all the api.parse.com will be closed?

**Comment by natanrolnik** [comment]
@kenglou 
Yes, you right. Requests to api.parse.com after 28 Jan 2017 will fail. 
Parse -server relies on MongoDB, so I don't believe other types are an option.

**Comment by drew-gross** [comment]
Thanks for answering @natanrolnik! There is no downtime with the database migration tool. Other DB providers may be creating their own non-mongodb solutions however I suggest that you begin planning your migration immediately instead of waiting to see what they come up with.

We are currently planning to refuse all requests to api.parse.com starting on January 28th, however we have heard concerns about Parse for IoT that can't be updated, so we are going to consider other solutions for those customers, like setting up a redirect from api.parse.com to a hosted parse-server. However, we aren't sure if we will make that solution available to everyone or only Parse for IoT users..
