### ISSUE TITLE
Failed to validate this access token with Facebook.

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-server#2569]
Please read the following instructions carefully.

Check out https://github.com/ParsePlatform/parse-server/issues/1271 for an ideal bug report. 
The closer your issue report is to that one, the more likely we are to be able to help, and the more likely we will be to fix the issue quickly!

Many members of the community use Stack Overflow and Server Fault to ask questions. 
Read through the existing questions or ask your own!
- Stack Overflow: http://stackoverflow.com/questions/tagged/parse.com 
- Server Fault: https://serverfault.com/tags/parse

For database migration help, please file a bug report at https://parse.com/help#report

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [ x] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [x ] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [x ] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

- [ x] You have filled out every section below. Issues without sufficient information are more likely to be closed.

--

### Issue Description

Our iOS client will not allow us to log into facebook anymore, since switching off of parse.com

iOS console output

```
2016-08-22 15:11:53.886 Likemoji[1012:334800] [Error]: {"code":1,"message":"Internal server error."} (Code: 1, Version: 1.14.2)
Uh oh. The user cancelled the Facebook login.
```

On parse server latest 2.2.18 the logs spit this out

```
2016-08-22T22:09:39.840519+00:00 app[web.1]: error: Uncaught internal server error. Failed to validate this access token with Facebook. undefined
2016-08-22T22:09:39.837296+00:00 app[web.1]: error: Error generating response. 'Failed to validate this access token with Facebook.' error=Failed to validate this access token with Facebook.
2016-08-22T22:09:39.858825+00:00 app[web.1]: Failed to validate this access token with Facebook.
```
```

  databaseURI: databaseUri || 'xxx',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'xxx',
  facebookAppIds: ['123456789'],
  masterKey: process.env.MASTER_KEY || '',
  restAPIKeY: process.env.RESTAPI_KEY || '',
  serverURL: process.env.SERVER_URL || 'https://xxx',  // Don't forget to change to https if needed
  fileKey: process.env.FILE_KEY || 'xxx',
  filesAdapter: new S3Adapter(
    process.env.AWS_ACCESS_KEY || 'xxx',
    process.env.AWS_SECRET_ACCESS_KEY || 'xxx',
    "bucket",
    {directAccess: true}
  ),
  push: {
    ios: [
      {
        pfx: 'xxxx', // Prod PFX or P12
        bundleId: 'xxx',
        production: true // Prod
      }
    ]
  }  
});
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.18
  - Operating System:     Heroku 
  - Hardware:             Heroku
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
  - MongoDB version: 3.2
  - Storage engine:  WiredTiger
  - Hardware:       Mlab
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Mlab

**Comment by steven-supersolid** [comment]
When I'm trying to debug issues like this I find the following approach helpful:
* Run with VERBOSE=1 (on heroku add a config variable VERBOSE with value 1)
* Try and run locally
* If you cannot run locally because a device is connecting to the server then record what the device requested using above logs and recreate using curl to a local server
* Find where in parse-server the string 'Failed to validate this access token with Facebook' occurs
* Go to your node_modules/parse-server/... folder and change this code to give debug more meaningful to your problem
* If the problem occurs only online (e.g. in heroku, EB) then you'll need to fork parse-server, add your debug to src, build with `npm run build`, remove the lib folder from .gitignore, push to your fork, use your fork as a git dependency.

Debugging FB authentication is fairly straightforward because it happens in facebook.js and is just a http request to graph.facebook.com. In your case it looks like the graph request is failing so either your server cannot talk to facebook or you are not providing an access_token in the correct format.

BTW if you look do a text search for facebookAppIds (set in ParseServer.js) you will see that they are unused in the code so I don't think this is the issue.

Hope this helps. It does look app-specific but there could be an issue that manifests itself only in your particular setup.

**Comment by flovilmart** [comment]
I'll have a look tonight

**Comment by flovilmart** [comment]
Yeah, I have a fix that properly handles facebookAppIds, but it would be better to move on with the generic format: `{oauth: {facebook: {appIds: ["app1", "app2"]}}}`

**Comment by gateway** [comment]
So I was able to get this resolved, but not 100% sure what the issue is.  My original deployment was using the Heroku button for the parse server example.  Since we were not testing FB login for a while this was unnoticed.  Then when testing our login system we where stuck with this issue.

After some debugging and elimiating each part.

Testing locally (worked)
Testing on a stage server (worked)
Production (didnt work)

Deployed parse server example this time w/o the Heroku button and all from the command line tools to deploy the code.  After this was done the FB login worked again.

I dont really call this resolves since really hard to tell what the difference between using the Heroku button and deploying the code yourself.

**Comment by flovilmart** [comment]
maybe we should close that one as it seems to be a misconfiguration problem on your side
