### ISSUE TITLE
Is it possible to implement replay using LiveQuery?

### ISSUE THREAD

**Issue by ssssssssssss** [ParsePlatform/parse-server#2613]
Dear gurus,

We'd like to implement a replay function for games. Our main flow works like following,

1. Our game is more like a quiz
2. Users insert their new scores in realtime manner, so the server keeps all the historic data for individual games.
ROW1: {"user":A, "duration":1000ms, "correct":1, "answered": 5, createdAt:xxx}
ROW2:{"user":B, "duration":1001ms, "correct":2, "answered": 5, createdAt:xxx}
ROW3:{"user":C, "duration":1010ms, "correct":2, "answered": 5, createdAt:xxx}
ROW4:{"user":A, "duration":1200ms, "correct":2, "answered": 6, createdAt:xxx}
ROW5:{"user":B, "duration":1203ms, "correct":2, "answered": 6, createdAt:xxx}
...

3. If another user joins the game later, we will present him historical data replaying based on time elapsed(duration), so we can tell which one is the best at this specific time.

IMHO, LiveQuery is great to push changes in realtime, but we don't know how to subscribe a time-based LiveQuery. Is that possible? 

Thanks.

**Comment by flovilmart** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #parse.com? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use Server Fault for questions about managing your own servers.

**Comment by ssssssssssss** [comment]
Thanks, here is the link.
http://stackoverflow.com/questions/39239517/is-it-possible-to-implement-replay-using-livequery
