### ISSUE TITLE
Local data Store (is making app to don't callBack)

### ISSUE THREAD

**Issue by maravilhosinga** [ParsePlatform/parse-server#2664]
Hi, i'm using Parse server and all is working fine except when i enable localdatastore, most 

1. saveInBackroud stop working and also 
2. SignUpInBackgroud is singin up a new user but, is not calling back, and it's being impossible to stop a progressDialog
3. Also not saving usersession on signup

       `Parse.Configuration config = new Parse.Configuration.Builder(this)
                .addNetworkInterceptor(new ParseLogInterceptor())
                .addNetworkInterceptor(new ParseStethoInterceptor())
                .applicationId(PARSE_APP_ID_DEV)
                .clientKey(PARSE_CLIENT_DEV)
                .server(PARSE_SERVER_URL)
                .enableLocalDataStore()
                .build();
       Parse.initialize(config);`

Help please

**Comment by flovilmart** [comment]
Code would help, logs from the interceptor too, as well as the logs from parse-server when running with VERBOSE=1

**Comment by maravilhosinga** [comment]
And please how can i set VERBOSE =1

**Comment by hramos** [comment]
Please refer to [this issue](https://github.com/ParsePlatform/parse-server/issues/1271) for an example of a great bug report.

Make sure these boxes are checked before submitting another issue -- thanks for reporting issues back to Parse Server!

- [ ] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [ ] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

**Comment by maravilhosinga** [comment]
Ok, i figured the same issue with parse.com hosted database, i will try to downgrade my Android Parse SDK to see how it will work.

**Comment by hramos** [comment]
Gotcha.

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
