### ISSUE TITLE
What happened to the parse core built with Go?

### ISSUE THREAD

**Issue by jyoon17** [ParsePlatform/parse-server#27]
In the past, you guys proudly announced that the core API server was rewritten in Go and I was really thrilled to see how you did it when I first heard the news. But now we have source code in Node.js out of nowhere..

Are you guys rewriting all the source code again?

**Comment by yuki-takeichi** [comment]
This is "Parse-compatible API" server. I guess it's totally different from Parse internal.

**Comment by anthonysg** [comment]
It would be nice to see an explanation from somebody at Parse about this.

**Comment by lacker** [comment]
The core API server is actually solving a lot of additional problems, because it's essentially massively multitenant. One server could handle a whole bunch of apps and deal with various operational edge cases. It's also entirely separated from cloud code / per-app javascript. Best practices for running your own server for a single app are pretty different. For someone running a single app, I don't think it would be the ideal fit to be running a go binary, plus separate custom js code in node.js. This setup seems far superior. And the code can be way, way simpler if it's just reimplementing a bunch of the Parse API rather than additionally porting a bunch of extra operational/logging stuff that only makes sense in a massively multi-app case.

**Comment by ahmedbaracat** [comment]
@lacker It would be great if you can tell me which one were you using in production, the Node.js or the GO server? or where you using a GO server that initiates/spawns Node.js?

**Comment by nige123** [comment]
I'm interested in this too? @lacker could you please outline the relationship between Go and Node.js in your running setup?

**Comment by lacker** [comment]
Parse.com runs the go server in production. By now there are also a lot of people running Parse Server in production as well, but not on parse.com.
