### ISSUE TITLE
Exception in Parse.Cloud.job causes parse server to stop completely

### ISSUE THREAD

**Issue by asdf01** [ParsePlatform/parse-server#2704]
Hey Guys

Thank you @flovilmart for adding the jobs end point to parse-server: 
https://github.com/ParsePlatform/parse-server/pull/2560

However testing it out, noticed that the parse-server stops completely when there is an error in the Parse.Cloud.job definition.  

Steps to reproduce:
- in your main.js find any Parse.Cloud.job definition
- add the line asdf.asdf before any async calls
- curl the /jobs endpoint you just modified

What you should see:
- error handling something similar to how the /functions endpoints behave

What you actually see:
- parse-server terminates

I am no node.js expert, but it looks like it has something to do with this line where it runs the job asynchronously in a call back using process.nextTick: 
https://github.com/ParsePlatform/parse-server/blob/master/src/Routers/FunctionsRouter.js#L69

For the reasons outlined in this page I found: 
http://snmaynard.com/2012/12/21/node-error-handling/#Exceptions
any errors in process.nextTick causes the node.js program to stop.  

Again, I am no node.js expert.  I tried a few things with no luck.  I will keep looking for solutions, but hopefully the solution is obvious to you node.js experts.  Thanks.

**Comment by flovilmart** [comment]
yeah, that's expected. We use process.nextTick to give your cloud code job a fresh call stack. Also we could have wrapped the call in to a try / catch block but that would only have had an effect on the current call stack, not any async calls internally.

The blog you're quoting while correct, is from late 2012, and don't take into account that we're running 'your code' on the top of a framework. 

If we'd run it 'synchronously' , without the process.nextTick, that would have pretty much the same effect, besides the fact that your call stack would not be fresh.

we can't really have error handling as the functions are as we don't immediately respond with the error, the jobs endpoint is not meant to be run synchronously, (that's why we use nextTick) to return the response, even before the job actually started.

What could be done, is surround the `jobFunction(request, status);`  into 

```
try {
  jobFunction(request, status);
} catch (e) {
  logger.error(`Error running job ${jobName} with ${jobId}`, util.inspect(e));
  status.error(e.message);
}
```

I don't believe that would really help as you'd need to go into your logs to see the coding errors of your jobs as any async call would not be catched by that:

ex:

if you job is:
```
request('http://my.serverer', function(err, res, body) {
   requesst('https://my.server.com', ...) // note the typo in request 
});
```

the server would still crash and burn without the ability to recover, as the callback of first request would already be in a new call stack.

**Comment by asdf01** [comment]
Hi @flovilmart 

Thanks for looking into this issue.  

> The blog you're quoting while correct, is from late 2012,

I wasn't suggesting that the article I linked contained a solution to the problem.  I was merely suggesting that the article confirmed my suspicions that errors in process.nextTick was causing the whole node.js application to stop completely.  

From what I remember of your comment in the original commit for the /jobs endpoint: 
https://github.com/ParsePlatform/parse-server/pull/2560#issuecomment-241275271
the async nature was the intended effect.  In that case, like you indicated, there is not much we can do apart from logging the error.  

Doing the try catch around the `jobFunction(request, status);` and simply logging the error was what I had in mind.  For our purposes that would be sufficient as it would stop the parse-server program from completely stopping.  

In your example, I don't know what you meant by the `status.error(e.message);` line.  I thought parse-server already responded to the /jobs/<job01> request before processing of the contents of process.nextTick begins.  

> any async call would not be catched by that:

I am not too worried by this.  Our cloud jobs definitions like our cloud function definitions already had an error handling block for the entire promise chain.  The parse.com variant simply put the error in the response: 
`response.error('error01')`
the parse-server variant leveraging your code would simply be changed to log the error:
`logger.error('error01')`.  

So that outlines what I'm going to our fork to cover our needs.  You've done a lot of work for parse-server so I respect what ever you decide to do for the github/parse-server code base.  

Thanks again for all your contributions.

**Comment by flovilmart** [comment]
If you end up implementing the try / catch, you should probably open a PR for it, and add the tests relevant to that particular enhancement so everyone can benefit the changes.

**Comment by asdf01** [comment]
Hi @flovilmart 

> you should probably open a PR for it

I'd be happy to contribute.  It's just that I wasn't too sure whether you approved of the approach.  In your [previous comment](https://github.com/ParsePlatform/parse-server/issues/2704#issuecomment-246532621) it sounded like you didn't think it would add too much value.  Anyway, I will get that sorted.

**Comment by flovilmart** [comment]
It doesn't add much but it's also not breaking anything nor deteriorating the experience, so I consider any contribution that help make the project more stable and friendly for everyone.
