### ISSUE TITLE
101 Object not found in Cloud Code

### ISSUE THREAD

**Issue by YungMims** [ParsePlatform/parse-server#2757]
Hi,

I'm having a strange problem with Parse-Server.

I get **sometimes** the following error:

> ParseError { code: 101, message: 'Object not found.' }

It usually happen after an error in cloud code, in whatever function that use the object even if there is no update in it (like the following function that just doing a find but still create the bug if it fail for any reason like a bad code line). However I'm not sure this is the cause.

I have that simple function in Cloud Code:

    const user = req.user

    const card_id = cid(req, user)
    const base_error = global.i18n.__('errors.default')

    if(!card_id) return res.error(base_error)

    console.log('CID: ' + card_id + ' | UID: ' + user.id)

    new Parse.Query(global.m.Card).get(card_id)
    .then((card) => {
      if((new Date) - card.updatedAt > OSC.syncDelay)
        return _CARD.sync(card.get('onum'))

      return card
    })
    .then((card) => {
      res.success(card)
    })
    .then(null, (error) => {
     if(Array.isArray(error)) error = error[0]

      console.log(error) // HERE is where the error is logged
      res.error(base_error)
    })

Here is what the console.log print:

> CID: PqOMwi5y60 | UID: QldBflokJV

Here is how the Card ACLs are defined (with an update, not at creation):

    const cardACL = card.getACL()
    cardACL.setReadAccess(user, true)
    cardACL.setWriteAccess(user, true)

    if(memory.admin) {
      cardACL.setReadAccess(memory.admin, true)
      cardACL.setWriteAccess(memory.admin, true)
    }

    card.setACL(cardACL)

Finally, this is what I have in my Database for the card object Permissions/ACLs:

    "_id" : "PqOMwi5y60",
    "_wperm" : [ 
        "role:Administrator", 
        "QldBflokJV"
    ],
    "_rperm" : [ 
        "role:Administrator", 
        "QldBflokJV"
    ],
    "_acl" : {
        "role:Administrator" : {
            "w" : true,
            "r" : true
       }
    }

Am I doing something wrong ?

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
