### ISSUE TITLE
Restricting access to only logged in users

### ISSUE THREAD

**Issue by khalilsarabey** [ParsePlatform/parse-server#2759]
Hello Parsers ! 

I'm building a mobile app and I'm using parse as my backend for the first time, and for what I'm trying to do, users should not be able to see or do anything if they're not logged in except for registering logging in, and here's where the problem happens. 

I know how this is supposed to be done so I'll describe it: 

0. The class I'm working is "PrivateThreads"
1. I created a role and named it "LoggedinUsers"
2. I went into the dashboard, clicked on security, unchecked everything for public, so basically public has no permissions at all whatsoever
3. In the same dialog, I added the role of LoggedInUsers and gave it a permission to create only
4. The class has a pointer to the User class, so I gave this pointer permission to find / get / edit / delete on the class PrivateThreads 

All sounds good and makes sense!

Here's the confusing part:
I created a couple of records in the dashboard, and I used postman, without a session token (X-Parse-Session-Token) if I try to access the PrivateThreads class to list all available records, it doesn't return any results, but it's not returning a permission denied message, the response I'm getting is: {"results": ""}
If I use a session token for a user that is not the actual creator of the record, I'm still able to access this record.

Expected behavior: 
1. I'm supposed to get a permission denied message if I'm not using a session token on any class that has LoggedinUsers role assigned to it.
2. I'm not supposed to be able to see anything that I did not create.

I'm doubting that the second point has much to do with the first point, cause before using this role everything was working as expected.

Any help with what could be going wrong is much appreciated.

Thanks!

Khalil

**Comment by jpv123** [comment]
I'm having a similar behaviour. I have a simple cloud code function that runs a query on a particular table.
```
Parse.Cloud.define("getRowOfTable", function (request, response) {
    if (request.user == null) {
        response.error(101);
    } else {
        var query = new Parse.Query("MyTable");
        query.equalTo("idUser", request.params.idUser);
        query.find({
            sessionToken: request.user.getSessionToken(),
            success: function (results) {
                response.success(results);
            },
            error: function () {
                response.error("Function failes");
            }
        });   
    }
});
```
 The ACL of the only row in that table is set to write for the user and everything else is off. All the read properties (The public and the row ones) are disabled. However the query is able to get the result with any valid session token of any user set in X-Parse-Session-Token 

```
{
  "result": [{
      "idUser": "LX3Gj2P4BP",
      "address": "Calle 1 #2 - 3 A",
      "city": "Abriaqui",
      "number": "31689966",
      "state": "Antioquia",
      "createdAt": "2016-09-21T15:50:47.715Z",
      "updatedAt": "2016-09-21T16:12:27.413Z",
      "ACL": {
        "LX3Gj2P4BP": {
          "write": true
        }
      },
      "objectId": "a2VovRqPO8",
      "__type": "Object",
      "className": "Address"
    }]
}
```

Any ideas? I think this is a bug. The expected behaviour is 

1) If all the read values of ACL and CLP are in off, queries should not return any object
2) If the read property of the ACL is set to read to only an user. That user should be the only one to be able to access the element, so if I set the X-Parse-Session-Token to another one different from his it must return an error

Sorry for my bad english

**Comment by jpv123** [comment]
Mi issue is working correctly on 2.2.21. Sorry

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.

**Comment by zh-wowtv** [comment]
Don't quite understand. Let's say if you define a Cloud code, then only the call to this cloud code will be restricted to logged in users. But if you have api key and url, anybody can write a JS client code to access any objects. Am I right?

So I think the best solution is to use dashboard to setup the class level permission.
