### ISSUE TITLE
Secondary Reads

### ISSUE THREAD

**Issue by halvini** [ParsePlatform/parse-server#2847]
We created 10 nodes with Parse Server and they killed our Mongo database's Primary.

Is there a way we can set set secondaryPreferred for the reads on parse servers otherwise the load will be put in the primary node?

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
