### ISSUE TITLE
Push notifications via REST

### ISSUE THREAD

**Issue by LaBrie13** [ParsePlatform/parse-server#2848]
I have a general question towards the push functionality:
Should this be usable in the meanwhile with an own parse server without usage of cloud code? 
Asking because I am inserting records into _PushStatus via REST, but there is no message received on the devices. All described configuration steps are done so I am wondering if it should be anyhow possible.

**Comment by bohemima** [comment]
Sending a push is more than adding a row to that collection. You should be able to use the REST api to use the correct "/push"-endpoint if you supply the masterKey.

https://github.com/ParsePlatform/parse-server/blob/master/src/Routers/PushRouter.js#L8

**Comment by LaBrie13** [comment]
I have started the parse server with a sender ID and an API Key for android. The client app has been configured as described. Now I am using a curl:
`curl -X POST \
    -H "X-Parse-Application-Id: appppppidddd" \
    -H "X-Parse-Master-Key: mmmmaaasstteerkeeyyyy" \
    -H "Content-Type: application/json" \
    -d '{
          "where": {
            "deviceType": "android"
          },
          "data": {
            "title": "Push Test",
            "alert": "Do you get a push???"
          }
        }'\   http://myserverIP:1337/parse/push`

Shouldn't that actually work?

**Comment by bohemima** [comment]
Looks ok, what does the parse-server say? Run it with VERBOSE=1.

**Comment by LaBrie13** [comment]
server states:
POST /parse/push { host: 'myhostip:1337',
  'user-agent': 'curl/7.45.0',
  accept: '*/*',
  'x-parse-application-id': 'appid',
  'x-parse-master-key': 'masterkey',
  'content-type': 'application/json',
  'content-length': '213' } {
  "where": {
    "deviceType": "android"
  },
  "data": {
    "title": "Push Test",
    "alert": "Do you get the push???"
  }
}
response: {
  "response": {
    "result": true
  }
}

**Comment by LaBrie13** [comment]
btw: in the google console I can see the GCM API is not used; I rechecked all the keys and the senderId to be sure, but everything looks fine. Still the message seems not to reach GCM.

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
