### ISSUE TITLE
app.post on parse heroku server is unauthorized

### ISSUE THREAD

**Issue by tanujgirish** [ParsePlatform/parse-server#2854]
I am trying to post to my server from twilio, but I am getting a 403 error. Basically my parse-heroku serve is rejecting any request from twilio. I am working with TWIMLAPP and masked numbers. I am having trouble posting to a function in my index file when a text goes through. In my TWIMLAPP my message url is https://parseserver.herokuapp.com/parse/index/sms Any help is appreciated. These are the errors in twilio 1) http://i.stack.imgur.com/OoyWq.png 2)http://i.stack.imgur.com/uPxAa.png
`var app = express();
app.use(require('body-parser').urlencoded());
app.use(function (req, res, next) {

// Website you wish to allow to connect
res.setHeader('Access-Control-Allow-Origin', 'https://www.twilio.com');

// Request methods you wish to allow
res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');

// Request headers you wish to allow
res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');

// Set to true if you need the website to include cookies in the requests sent
// to the API (e.g. in case you use sessions)
res.setHeader('Access-Control-Allow-Credentials', true);

res.setHeader("X-Parse-Master-Key", "xxxxxxx");

res.setHeader("X-Parse-Application-Id", "xxxxxx");

// Pass to next layer of middleware
  next();
});

app.post('/sms', twilio.webhook({ validate: false }), function (req, res) {
  console.log("use-sms")
  from = req.body.From;
  to   = req.body.To;
  body = req.body.Body;

  gatherOutgoingNumber(from, to)
  .then(function (outgoingPhoneNumber) {
    var twiml = new twilio.TwimlResponse();
twiml.message(body, { to: outgoingPhoneNumber });

res.type('text/xml');
res.send(twiml.toString());
  });
});`

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
