### ISSUE TITLE
Unable to send mail using Parse Cloud.

### ISSUE THREAD

**Issue by badrinathvm** [ParsePlatform/parse-server#2874]
### Issue Description

Unable to send mail in swift using Parse Cloud , Response object is appearing as nil.

 Also seeing Invalid function. (Code: 141, Version: 1.14.2) in error logs

Code :  

```
PFCloud.callFunction(inBackground: "Welcome Email", withParameters:
            ["email" : "\(userEmail)"]) { (response, error:Error?) in
     
                let hello = response// as? String
                print(hello)   // printing as nil
        }
```

My Cloud code is /cloud/main.js 

```
Parse.Cloud.define('email', function(req, res) {
  res.success('Hi');
  var Mailgun = require('mailgun');
  Mailgun.initialize('services', 'api key');

  var mailEmail = request.params.email;
  console.log("Mail is " + mailEmail)
  Mailgun.sendEmail({
    to: "mailEmail",
    from: "Mailgun@CloudCode.com",
    subject: "Welcome!",
    text: "Hello "  + ", \n Thank you for signing up."
  }, {
    success: function(httpResponse) {
      console.log(httpResponse);
      response.success("Email sent!");
    },
    error: function(httpResponse) {
      console.error(httpResponse);
      response.error("Uh oh, something went wrong");
    }
  });
});
```

[FILL THIS OUT]

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. [FILL THIS OUT]
2. [FILL THIS OUT]
3. [FILL THIS OUT]

#### Expected Results

Should be able to send mail

#### Actual Outcome

Not able to send mail , seeing " Invalid function. (Code: 141, Version: 1.14.2) "

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 
  - Operating System:    Sierra
  - Hardware:             Mac 
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
  - MongoDB version: Latest
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]

  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [FILL THIS OUT]

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

<img width="699" alt="screen shot 2016-10-15 at 2 46 17 pm" src="https://cloud.githubusercontent.com/assets/1479179/19413575/3068d648-92e6-11e6-80b4-73e76e9c6887.png">

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
