### ISSUE TITLE
parse for on-demand apps

### ISSUE THREAD

**Issue by sabirmgd** [ParsePlatform/parse-server#2901]
background: I got a request from a client to develop an Uber like app, its a mobile app for android and for iOS, the app will be deployed in only one country and the pressure definitely will be less than the existing Uber app, I came across parse.com as service but I still have some doubts.

since Parse.com will shutdown on jan 2017, I did a bit of research and I thought of using the parse server with a cloud service such as digitalOcean.

now, is parse.com capable of handling a lot of real time requests that will be made by an Uber like app? for example, the drivers location will be updated regularly whenever they are available, the riders location will also be updated when they open the app.

is parse as server hosted in digitalOcean be a good choice and will be able to handle the requests? or at the end it lies down to digitalOcean capabilities?

**Comment by flovilmart** [comment]
It Would mostly lie down to your hosting service and database capabilities. Parse-server is designed to scale horizontally in a stateless manner.

**Comment by sabirmgd** [comment]
great, this is regarding the the scalability, will not having an official release of liveQuery for android be a limitation for this on-demand (real time ) kind of apps ?

**Comment by chesterhawkins** [comment]
@sabirmgd I'm also currently developing an app that uses parse-server + digital ocean and my app relies heavily on live query. I also use user location data that is updated about 2 timers every minute and so far things are great. BUT, since I'm only in beta I haven't scaled to a bunch of users yet.  Digital Ocean allows you to bump up to more RAM and CPU speed whenever you need to so I think things should be fine.  I've been wondering about liveQuery for Android as well but I guess I'll have to cross that bridge when I get there.  Push Notifs is an option but it's not exactly real time or reliable and users can disable them at anytime.

**Comment by sabirmgd** [comment]
@chesterhawkins sounds great! [you can follow this issue for the liveQuery ](https://github.com/ParsePlatform/Parse-SDK-Android/issues/437) if you are not already doing.

**Comment by flovilmart** [comment]
@sabirmgd we're working on one, there is actually an implementation that we have in staging environments that look very promising, and on par with the iOS LiveQuery client. Stay tuned it may be released soon.

**Comment by flovilmart** [comment]
Closing as it seems everything has been properly answered
