### ISSUE TITLE
Heroku Cloud Code Access

### ISSUE THREAD

**Issue by listingboat** [ParsePlatform/parse-server#2945]
I have an app that is a node/express app written on top of cloud code.  It is deployed and functional on Heroku.  However, we get random performance issues.  I suspect this is due to the fact that the cloud code is competing with external web requests to the same URL.

In our config, the serverURL is set to https://<appname>.herokuapp.com.  Which mean the Parse cloud code calls to parse are going out over the internet instead of directly to localhost.

Is there a serverURL config that would work for localhost on Heroku.  My many attempts have failed.

**Comment by flovilmart** [comment]
try localhost:8080 or whatever port is heroku listening on. Otherwise, you can try to use PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS=1 as an environment variable.

This removes the HTTP roundtrips with CloudCode <-> parse-server. 

Before using that, you have to make sure that your cloudCode doesn't contain `Parse.Cloud.useMasterKey()` and `Parse.User.current()`

**Comment by listingboat** [comment]
I am aware of the experimental direct access.  I understand it is slated for version 3.x is that correct?

**Comment by flovilmart** [comment]
it's available right now, protected by the env variable. It's scheduled for a later version.

**Comment by woodardj** [comment]
Sorry for jumping on an old thread — to clarify, the reason not to use "useMasterKey" with `PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS` is because it's a security risk? Is that accurate?
