### ISSUE TITLE
Add ability to live update cloud code without a Parse Server restart

### ISSUE THREAD

**Issue by felipemobile** [ParsePlatform/parse-server#2960]
Hello, from what I've tested Parse cloud code can only be updated after a Parse-server restart.

I'd like to check if we can add the ability to handle live updates on cloud code without restarting the service. The second point is to add a secure approach to avoid Parse-server not being able to run when errors are found in cloud code.

Node: 4.6.1
Parse Server: 2.2.23
$ forever start index.js

Ps: I use forever package to ensure that node script runs continuously.

**Comment by flovilmart** [comment]
The main issue with enabling that feature is that cloud code is cached by node's require. See [here](https://github.com/ParsePlatform/parse-server/blob/master/src/ParseServer.js#L241).

We'll be unlikely to provide a workaround to that behaviour without a major refactor of the cloud code loading mechanisms.

**Comment by michaelsalvador** [comment]
Hello,

I'm new to all of this, and I'm wondering if you could answer a quick question for me.
I have already deployed my parse-server with Heroku and it's operating smoothly. I now wish to add push notifications, so my question is this: after making updates to the cloud/main.js file, how do I update the server to make them work? I'm hesitant to start messing around with the command line as I'm afraid I'll mess something up. 

Thanks!

**Comment by flovilmart** [comment]
You deploy again to heroku with your updated code.

**Comment by michaelsalvador** [comment]
Lol thanks for response. Sorry for trivial question

**Comment by michaelsalvador** [comment]
Just have one more quick question if you don't mind.

I'm reading about how to deploy to Heroku again, and I found a guide on Heroku.com that says I need to clone my app's repository, make the necessary changes, and execute these commands to redeploy: 

$ git add .
$ git commit -am "make it better" (I know that this is arbitrary)
$ git push heroku master

The repository I clone gives me a folder with my app's name, but the text in the index.js seems to be the stock text without any modification, and is different than that of the one located in parse-server-example on my computer. The folder also doesn't contain things like "Parse-Dashboard". This confuses me, because I would think that the folder would be the same as the one I deployed originally. So my question is, if I made updates in the index.js that I cloned and deployed that, would the server update correctly? Or does it seem like I'm doing something wrong based on what I told you?

**Comment by flovilmart** [comment]
When you push your local repository branch (master) to heroku, this is what you should get running on heroku. 

I didnt  use heroku much, but I don't recall cloning from the heroku origin, just pushing there when I have a new version to deploy. Not sure it helps though. Without more knowledge of what you did before. I also don't use, nor recommend using parse-server-example as it can be misleading in many ways.

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
