### ISSUE TITLE
PFFiles and App Transport Security

### ISSUE THREAD

**Issue by pranjalsatija** [ParsePlatform/parse-server#3008]
### Issue Description
My Parse Server is running on AWS. I've configured SSL for the server and all **non file** related requests between clients and the server are encrypted using SSL. However, I've noticed an issue recently: when I attempt to download files, I'm greeted with an error from App Transport Security on iOS. If you aren't familiar, App Transport Security basically blocks all non SSL network requests. Although my Parse Server has SSL, file downloads are not using https URLs. Here's an example of an error returned by iOS:

```
Error Domain=Parse Code=100 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." UserInfo={code=100, NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection., originalError=Error Domain=NSURLErrorDomain Code=-1022 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection."...
```

I know I can disable App Transport Security but that's frowned upon by Apple and I really don't want to do so. If there's another possible fix, I would love to hear about it.

### Steps to reproduce

1. Host a Parse Server.
2. Configure SSL for the server.
3. Attempt to download a PFFile from the server on an iOS device.

#### Expected Results

The file downloads successfully and is usable like any other PFFile.

#### Actual Outcome

App Transport Security prevents the file from being downloaded.

If anyone can shed some light on this, please let me know. Until then, I believe that this is definitely an issue.

**Comment by apersaud** [comment]
Hopefully this helps since I had a few issues related to this:

First, make sure that the `url` field of the PFFile that you are trying to load is of type `https`. I've noticed that some PFFiles when using the hosted parse solution (uploaded through http://api.parse.com) always use `http` instead of 'https` which breaks transport security. This means you would still have to add an exception in the Info.plist file or in Swift/Object-C rewrite the URL to use https. This is pertinent if you situation is having migrated a Parse app to your own Parse Server but still have old Parse files in your database.

The second issue could be the base URL for your files. Assuming you are using S3, make sure the S3_BASE_URL parameter of your S3 adapter it starts with `https` and [has the proper bucket policy](https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters#configuring-s3adapter). This would then allow that PFFile instances returned by your server will start with `https`.

If all else fails, I would still add a exception in your `Info.plist` file for all files hosted by Parse and in your S3 bucket:
![screen shot 2016-11-03 at 6 56 05 pm](https://cloud.githubusercontent.com/assets/127068/19991952/3dbdfb1e-a1f7-11e6-8810-83a0e0120868.png)

Of course, I would add, you might have your own domain to host your own files, so you might want to add that as well. 

Hopefully this helps a bit.

**Comment by pranjalsatija** [comment]
@apersaud First of all, thank you so much for the help! I'm not using hosted Parse at all, and my app is completely independent of the original Parse service. I've checked the URLs for the files I'm loading, and they all begin with `http://`. I know that I can fix the issue by change that to `https://` but how would I do that with the Parse SDK for iOS? It doesn't let you change the `url` property on PFFile. Could you let me know how you think I should go about doing that?

**Comment by apersaud** [comment]
Ok, assuming this app is a fresh app and was never migrated from hosted Parse:

You need to modify your `filesAdapter` in your Parse Server configuration to have an baseURL with https. See an example configuration with example baseURL. This will make sure all Parse File urls are returned with the proper URL containing your `baseUrl` (which should be https).

```javascript
  opts.filesAdapter = new S3Adapter(
    env.S3_ACCESS_KEY,
    env.S3_SECRET_KEY,
    env.S3_BUCKET, {
      region: S3_REGION,
      directAccess: true,
      bucketPrefix: env.S3_BUCKET_PREFIX,
      // This is the configuration you want.
      baseUrl: env.S3_BASE_URL, // ex. 'https://mybucket.s3.amazonaws.com
      globalCacheControl: 'public, max-age=8640000'
    }
  );
```

**Comment by pranjalsatija** [comment]
@apersaud Really sorry about the late reply, but your fix worked! Thank you so much for the help. I'm going to go ahead and close the issue now. Once again, thank you.

**Comment by Technowise** [comment]
I got this fixed after I set publicServerURL configuration for the Parse Server. I do not have public access to the S3 bucket, so I could not access it with "directAccess" set to true.

This configuration is not documented anywhere . I feel this really has to be documented.

**Comment by flovilmart** [comment]
@Technowise, can you make a PR on the read me of the S3 adapter?
