### ISSUE TITLE
Query all parse file

### ISSUE THREAD

**Issue by AnChiChang** [ParsePlatform/parse-server#3019]
I had read ticket #1023 and understand implement delete all unused file is hard.
Can I know how to get all PFFile by query or the other way, then I can check my class and delete via RestAPI.

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
