### ISSUE TITLE
bad request when accessing cloud code using javascript sdk

### ISSUE THREAD

**Issue by dhemitus** [ParsePlatform/parse-server#3031]
cloud code working well if i'm using rest api but its failed when i'm using javascript sdk and it's return 400 (bad request).
this is my cloud code:
`Parse.Cloud.define("testing", function(request, response) {
    response.success("It works!");
});`

and this is my rest api request:
`curl -X POST \
-H "X-Parse-Application-Id: ${mysecretestring}" \
-H "Content-Type: application/json" \
https://myhosting.herokuapp.com/parse/functions/testing`

and this is my javascript code:
`Parse.Cloud.run('testing').then(function(r) {
     console.log(r);
});`

this is error message:
POST https://myhosting.herokuapp.com/parse/functions/testing 400 (Bad Request)
so, what's wrong with that code?

thank you

**Comment by mmahgoub** [comment]
Same error

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
