### ISSUE TITLE
Logs on Parse-Server.

### ISSUE THREAD

**Issue by kwstasna** [ParsePlatform/parse-server#3062]
- [x] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [x] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [x] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

- [x] You have filled out every section below. Issues without sufficient information are more likely to be closed.

--

### Issue Description

One friend got an issue with the Police. 
Before some months the _User A_  commented on a picture of _User B_ some insults. And of course the admin banned the _User A_.
Although _User B_ made a complaint to the Police about _User A_.
Yeah seriously. And the Police asked from the admin to give them the logs to see the IP of _User A_ and find him. If the admin has no logs with the IP he will get charged for cover up !!!
So i come to my question now. With the logs that parse-server has, there is no way for someone to find out in the above situation, what the IP of the user is.

How can we workaround something like this?

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.25beta.1
  - Operating System:     Ubuntu 14.04 x64
  - Hardware:             unknown
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Digital Ocean

- **Database**
  - MongoDB version: [FILL THIS OUT]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): DigitalOcean

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.

**Comment by kwstasna** [comment]
@hramos  http://stackoverflow.com/questions/40874851/logs-on-parse-server

Thanks a lot !

P.S. I would love to hear your thought if there was any case like this when parse.com was on 🔥
