### ISSUE TITLE
getting a [Error]: bad atom when getting an Array of JSON objects. 

### ISSUE THREAD

**Issue by farhansyed9** [ParsePlatform/parse-server#3073]
I have an array of JSON objects in Parse Dashboard, when i get this array i turn it into an dictionary and then put it back to an NSArray like so:

```
 for (NSDictionary *objects in userObject[@"userInterests"]) {
        
        NSMutableArray *personType = [[NSMutableArray alloc]init];

        personType = [objects valueForKey:@"personType"];
        
        
        NSLog(@"%@",personType);
        
    }
```
When this is run, I get an error of "[Error]: bad atom: [object Object] (Code: 107, Version: 1.13.0)"

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
