### ISSUE TITLE
re-send email verification ?

### ISSUE THREAD

**Issue by yaaminu** [ParsePlatform/parse-server#3088]
Sometimes a mail may not be delivered for one or two reasons. How do I try resending email verification in such situations?

**Comment by FridaySG** [comment]
Write a Cloud Code function and implement a mail provider. Mailgun has a a library you can use with Cloud Code I believe. Here's an example of someone doing so here:

https://github.com/ParsePlatform/parse-server/issues/1258

**Comment by AmrKafina** [comment]
In the parse hosted service, you can resend the verification email by re-setting the email of the user. You can just toggle the last character of the user's email and reset it, and parse will send the verification email again. 

Not sure if this functionality is still present on parse-server though.

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
