### ISSUE TITLE
Need info - about the Javascript sdk for the migration

### ISSUE THREAD

**Issue by rosarioconti** [ParsePlatform/parse-server#309]
I'm using at the moment the following libraries on the client side for javascript.
 I was wondering what I'm suppose to do with these libraries right now.

1) Should I download these libraries and make them available on the heroku server ?
2) Do I need to do any modification or are in place? 
 Thanks for the advice.

      <script type="text/javascript" src="https://www.parsecdn.com/js/parse-1.3.5.min.js"></script>
      <script type="text/javascript" src="https://parse.com/assets/main.js?1ee4d71"></script>

**Comment by drew-gross** [comment]
You will have to do that, but unfortunately that won't be enough by itself. You will also need to update the JS SDK version in your app to be able to use parse-server. There should be very few breaking changes to the parse JS SDK, so that should hopefully be easy. You will also then need to make sure you are retrieving the files from your heroku server, your own CDN, or somewhere else that you have some control over.

**Comment by rosarioconti** [comment]
So that may explain also why when I try to download an image from the server by the web app it always return (still) the files.parse.com ...  path .  
 I did change the parse server url , that's not an issue, my question is related to the image download which is not working as expected.

**Comment by drew-gross** [comment]
Yep, your files are not migrated as part of the existing migration process. We are working a tool that will help you migrate to your own S3 bucket.
