### ISSUE TITLE
getSessionToken() on queried user object is always undefined

### ISSUE THREAD

**Issue by danepowell** [ParsePlatform/parse-server#3098]
I'm trying to implement an alternative authentication function in Cloud Code that should accept a "pairing code" (some unique field on user objects) and return a _new_ session token for the corresponding user.

According to [the documentation](https://github.com/ParsePlatform/Parse-SDK-JS/blob/v1.9.2/src/ParseUser.js#L346), this should be as easy as querying for the user and then returning getSessionToken(). However, getSessionToken() always seems to return undefined, even when using the master key.

Am I missing something? Is there any way at all (even with a master key in Cloud Code) to generate a new session for a user without logging in with a password?

````
var query = new Parse.Query(Parse.User);
query.equalTo("code", request.params.code);
query.first({
  useMasterKey: true,
  success: function(user) {
    if (user !== null && typeof user === 'object') {
      var token = user.getSessionToken();
      // token is always undefined here
      response.success(token);
    }
    else {
      console.log("User not found.");
    }
  },
  error: function(error) {
    console.log("Query error: " + error);
  }
});
````

I originally posted this for the Parse JS SDK, but I think this is actually a Parse Server issue, since there's no way a client could generate a session token on its own: https://github.com/ParsePlatform/Parse-SDK-JS/issues/379

### Environment Setup

- **Server**
  - parse-server version: 2.2.19
  - heroku
  - mlab

**Comment by flovilmart** [comment]
> trying to implement an alternative authentication function in Cloud Code that should accept a "pairing code" (some unique field on user objects) and return a new session token for the corresponding user.

Look into the authData alternatives, they are meant for that, the auth adapters are receiving a hash for a certain user (that can be a token validated against your custom logic). 
The main benefit of not doing that in cloud code is that your code will be integrated the same way Facebook, twitter auth etc.. are integrated. 

ex: https://github.com/ParsePlatform/parse-server/blob/master/src/authDataManager/instagram.js#L6

Basically, you would pass on startup the module you want to use for your custom auth:

```
{ appId: "my-appId",
  oauth: {
     "custom-auth": {
          validateAppId: function() {}
          validateAuthData: function(authData) { /*validate auth data*/ }
      }
}
``` 

Then on the clientside:
https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/ParseUser.js#L642

```
Parse.User.loginWith("custom-auth", { authData: { token: "....", id: "unique-id" }})
```

Note that the `id` is required so you can properly update the tokens when whey become invalid and uniquely identify your users, this can be a username or an email.

## For the sessionToken:

the sessionToken is not a property of the user but on the _Session object. Those sessions are created per `installationId` in order to let the user see it's logged in sessions and revoke them.

Your strategy ~could~ work if you create a _Session object with the user and the installationID but I would recommend you try the method above.
