### ISSUE TITLE
How to integrate parse server Angular 2.2.1 using REST API ?

### ISSUE THREAD

**Issue by devrockzz** [ParsePlatform/parse-server#3120]
Hi,

I am not finding any documentation how to integrate parse with angular2 app using REST API , please guide me how to integrate it mainly how to set service .

**Comment by kulshekhar** [comment]
Why not use the Parse javascript SDK?

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.

**Comment by devrockzz** [comment]
Thanks Hramos
