### ISSUE TITLE
Custom Parse.Object id

### ISSUE THREAD

**Issue by oallouch** [ParsePlatform/parse-server#3125]
Hi,
I'd like to have some Pointers using custom references (for durability).
I know (think?) I can't change the Parse.Object ids using the SDKs.
Is it ok to change the ids using direct mongodb queries ?
Or is there a possibility to tell the framework "for this Class, use this property as the id for Pointers" ?

Just checking.
Thx a lot in advance (as always),

Olivier

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
