### ISSUE TITLE
does LiveQuery support use masterkey to bypass ACL permission? (eg: query.subscribe({useMasterKey: true}))

### ISSUE THREAD

**Issue by postgetme** [ParsePlatform/parse-server#3139]
my code running on backend, need to live query many users data, is there a way to do this? thanks!

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.

**Comment by postgetme** [comment]
thank you!
my question: [http://stackoverflow.com/questions/40880566/does-livequery-support-use-masterkey-to-bypass-acl-permission](http://stackoverflow.com/questions/40880566/does-livequery-support-use-masterkey-to-bypass-acl-permission)
