### ISSUE TITLE
webwhook integration 

### ISSUE THREAD

**Issue by jigneshk** [ParsePlatform/parse-server#3309]
Hello Team,

I have migrated my parse app to our own server and api works well.

But I don't know how to access webhook using get method.

Our api is working well with following URL.

http://ec2-xx-xxx-xx-xxx.us-west-2.compute.amazonaws.com:1337/parse/functions

And the old webhook url is as below.

http://xxxxxxxx.parseapp.com/webhookname?param1=123&param2=xyz 

Can you please let me know what will be the new URL for webhook on migrated instance?

Thanks
Jignesh

**Comment by rvitorper** [comment]
Hi there,

Web hooks implemented right now are either function or trigger and happen to fire as soon as you call the function or modify the database respectively. Hence, there is not a defined web hook endpoint.

Best Regards,
Ramon

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
