### ISSUE TITLE
Nested query causing permission issues

### ISSUE THREAD

**Issue by manishsangwan** [ParsePlatform/parse-server#3323]
In my `Role` class i have a field `firmId` that stores the pointer to `Firm`  class.

In my cloud code i query using master key. so when i query on `Role` class including `Firm`

```
// roleId variable has roleId
var query = new Parse.Query(Parse.Role);
query.equalTo('objectId', roleId);
query.include('firmId');
query.first({useMasterkey: true})
          .then(function (role){ ....});
```

i get my Role object with firm included.

but when i query using or (nested query)

```
var queryFirst = new Parse.Query(Parse.Role);
queryFirst.equalTo('objectId', roleId);

var querySecond = new Parse.Query(Parse.Role);
querySecond.equalTo('otherField', someVal);
                                        
var query = Parse.Query.or(queryFirst, querySecond);
query.include('Firm');
query.first({useMasterkey: true})
         .then(function(role){......});
```

this gives me error

```
 ParseError {
  code: 119,
  message: 'Permission denied for action get on class Firm.' 
}
```

I am using mater key in both cases.

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
