### ISSUE TITLE
Failed to load resource (unauthorized) - Status 403

### ISSUE THREAD

**Issue by maxlein** [ParsePlatform/parse-server#3339]
I try to run the test.html of the parse server platform but it gives me the above status error.
I have filled out the files with all the config thats needed. (app.json, app.yaml, index.js)

When I try to call parse via "curl -X GET   -H "X-Parse-Application-Id: ..." I get data from my classes.
Also my iOS app is working, only web doesn't work as expected...
Can someone tell me what I might have done wrong?

**Comment by natanrolnik** [comment]
@maxlein i assume you are trying to use the JS SDK correct? Try to initialize the SDK with the JavaScript key (configure one in the Server if needed). That should fix it.

**Comment by maxlein** [comment]
Thanks for the reply. That could be the problem, but in the parse server example I can't find anything like a ParseClientConfiguration. There are just  XHR requests like  "XHR.GET('/parse/classes/GameScore');" 
And if I want to include parse on the client like this: "var Parse = require('parse/node');", I get something like "require not found" although the same works on server side.
But I am not the most experienced in web apps as you might have realized ;)

**Comment by natanrolnik** [comment]
In the client you should do `var Parse = require('parse');`, without the `/node`. That goes only when using it from node itself, not from web clients. 
I'll assume it's misconfiguration of keys, it's not the first time something similar is posted here (specially because your GET requests work via curl), so I'm closing it for now. Feel free to post here if that indeed was the problem.
