### ISSUE TITLE
can't create new user from cloud code running on Parse Server (on aws). I get 107 parse error code and  nginx/1.10.1 Bad Request. on localhost it works.

### ISSUE THREAD

**Issue by Tomersteps** [ParsePlatform/parse-server#3345]
this is my code:
```javascript
var tempPass = genRandomPass();
var user = new Parse.User({
    username: email,
    password: tempPass,
  });

user.signUp(null, {
    useMasterKey: true,
    success: function (createdUser) {
      var link = inviteLink(email, tempPass, physio.get('lang'));
      sendInvitationEmail(email, physio, details, tempPass, {
        success: function (httpResponse) {
          console.log("User " + createdUser.id + " created, and sent email: " + httpResponse.status);
          response.success({
            user: createdUser,
            inviteLink: querystring.escape(link)
          });
        },
        error: function (httpResponse) {
          console.error("user " + createdUser.id + " created, but couldn't email them. " + httpResponse.status + " " + httpResponse.text);
          response.error({
            msg: "user " + createdUser.id + " created, but couldn't email them. " + httpResponse.status,
            inviteLink: querystring.escape(link)
          });
        }
      });
    },
    error: function (_user, error) {
      response.error("parse error: couldn't create user " + error.code + " " + error.message);
    }
  });

my db is mongodb (on mLab). I get the last error from the code - "parse error: couldn't create user... Received an error with invalid JSON from Parse... Bad Request".

**Comment by Tomersteps** [comment]
the request was too large for the current configuration of nginx.

**Comment by natanrolnik** [comment]
@Tomersteps can you please indent your code and format [the markdown correctly](https://guides.github.com/features/mastering-markdown/)?

**Comment by Tomersteps** [comment]
I hope it's ok now. I think the problem is that I need to enable CORS on nginx. I tried to do it but with no success..

**Comment by Tomersteps** [comment]
When I resend the request using Firefox an OPTION request is made that returns 200 and in the console it says:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://my-parse-server-on-aws/parse/functions/cloudFunction. (Reason: missing token ‘cache-control’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).

**Comment by hramos** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
