### ISSUE TITLE
Android SDK Attention!

### ISSUE THREAD

**Issue by nitrag** [ParsePlatform/parse-server#3356]
Sorry to post this in the wrong place, on purpose. **The Android SDK is in dire need of some TLC**. I however am not an Android Dev. I am here to encourage experience Java devs to step-up, as **flovilmart** has done for parse-server, and ask Facebook (@nlutsenko) for administrative rights to [Parse-SDK-Android](https://github.com/ParsePlatform/Parse-SDK-Android) so we can push development forward. The iOS SDK is getting some love but no attention at-all for Android.

There are many many nuance bugs, many are already in PR Stage waiting to be approved thanks to some of the devs listed below. 
### I would hate to see all this work going into parse-server be for naught because the SDK's have major flaws that results in hours of troubleshooting and causes new devs to become frustrated and walk away.

@sashakhail, @natario1, @jianwatertown, @mlauwers-edentify, @Joelo14, @rebahbouchaib, @dkuspawono, @nonda, @Ilhasoft, @evocodes just to name a few, please also comment your concerns to bring attention to this issue.

_Even though this is in the wrong place, can we please keep it open for 7 days to get the attention it needs?_

**Comment by MartinHerman** [comment]
Fully agree, the saddest part is that Parse Server and the iOS SDK are actually powerful, well maintained repos.

To be honest, I am pretty confident a major update of the ParsePlatform might be coming up soon, based on numerous [answers](https://github.com/ParsePlatform/Parse-SDK-Android/issues/437) (scroll down). Too bad there are no official news.

Still - even with no update to the client SDKs - if ParseServer keeps moving forward like it did in 2016, it will stay a viable development tool for me. The speed/cost at which you can develop apps at a proof-of-concept level isn't comparable to any other PaaS out there. Even without the client SDKs, the REST API is a reasonable fallback.

**Comment by natario1** [comment]
> and causes new devs to become frustrated

Old devs as well. FWIW I agree with the OP.

I’d like to contribute, but we need a present, experienced developer doing at least some coordination (and that is not me for sure). Current maintainers sadly have stepped down from this role as well. **We have issues that end with ‘please at least say something’**.

> I am pretty confident a major update of the ParsePlatform might be coming up soon

I am not. Plus, it might introduce LiveQuery, but there are 100+ open issues, ignored PRs ([this one](https://github.com/ParsePlatform/Parse-SDK-Android/pull/452) being the saddest), minor and major flaws. Don’t want to get technical, but I **can’t believe ParseObject is still not Parcelable**. That itself should make every experienced dev to not even consider Parse. 

I have already seen comments here and there @ stack overflow discouraging newcomers about Parse. And I myself would go for something else if I were to start from scratch.

The SDK was an incredible effort, I am grateful to whom worked on it, and it’s sad to see it go. I wouldn’t say the REST API is a *reasonable* fallback, honestly. There are alternative services out there. We need client libraries. Moreover, the Android SDK crumbling down **will have an impact on other SDKs** as well. Quoting @benitech from the other post,

> yea, doesn't seem to be much going on in the "Android-SDK" repo at all. Doesn't make sense to use any feature which is released for iOS and almost 4 months later has no compatibility with Android.
> If it continues like this, better consider other options.

I hope the Parse Server team would let this issue open until it is solved somehow.

**Comment by jiraya85** [comment]
@nitrag , @natario1 : I totally agree with you. Parse for Android needs more consideration and some issues have to be resolved.

**Comment by MartinHerman** [comment]
@natario1  would you elaborate on 
> There are alternative services out there. 

While I've worked on Firebase projects last year, it wasn't a match to Parse's simplicity. The same goes for AWS Mobile Hub.

I fully agree with you on the necessity to upgrade the client SDKs - but why still maintain / add features to Parse Server without the intention of upgrading the client SDKs? I believe most projects running on Parse are mobile apps... 

If its really over with the Parse Platform, someone should already rip the bandaid and get it over with...

**Comment by natario1** [comment]
> While I've worked on Firebase projects last year, it wasn't a match to Parse's simplicity

It might not, but hey, corporate backing is better than no backing at all. Also, ‘simplicity’ breaks down when you find yourself spending weeks debugging nasty internal bugs. I agree Parse is still the best service for AnyPic / AnyWall apps. But for anything more complex, the SDK *needs* some love at this point, IMO.

> but why still maintain / add features to Parse Server without the intention of upgrading the client SDKs?

Yes, that makes no sense. If Parse Server wasn’t so incredibly improved in the last year we probably wouldn’t be here struggling about android.

**Comment by flovilmart** [comment]
@natario1 Most of the (almost every) new features added to parse-server have been contributed by people outside parse/facebook. I don't believe anyone has risen to take over that SDK and start contributing and fixing those issues you mention. 

I am not part of Facebook or parse, I contributed on my own time to parse-server. I haven't seen this kind of activity on the Android SDK, and no one can force the community to come together to maintain that project.

It seems that you all want to see those SDK well maintained, and evolving, I would love to see it too. This starts with contributing, answering the issues etc... 

If no one is ready to take over, the community 'ripped the band-aid' themselves.

**Comment by natario1** [comment]
@flovilmart sure, this is not a corporate rant against Facebook or Parse (not mine at least).

I think the goal of the OP is ask Facebook to open up the maintainance part to someone else, and to find that someone else. Right now no one is even merging PRs. And that is discouraging for anyone else.

That’s what I would like.

**Comment by benitech** [comment]
As someone who is not a developer, i was very disheartened by the minimal progress on the Android SDK personally, especially after i had made the choice to start my project with Parse (even after the parse.com shutdown announcement) assuming that the community would really step in big time. Which they did on the Parse-Server for sure.

As of now, i have had to spend considerable time and effort in moving away from whatever i was using in Parse Server. I would personally not recommend any new project with Parse.

Harsh but real from a PM perspective.

**Comment by benitech** [comment]
On another note, the amount of time i had to spend to simply get oAuth working was just unreal. @flovilmart was very helpful always, but everyone will note there is still not a simple writeup "how to for dummies" anywhere

**Comment by flovilmart** [comment]
> assuming that the community would really step in big time

The community is not something magic you can invoke to solve your project, if you're a PM, you know developers, and if you know developers you could have enticed them to become that community.

> i have had to spend considerable time and effort in moving away from whatever i was using in Parse Server

So you don't use parse-server anymore? Not sure you're adding anything constructive to the discussion besides criticizing the lack of community support for the android SDK.

> everyone will note there is still not a simple writeup "how to for dummies" 

No there isn't, also nothing prevents you to do it once you managed to get it working.


I am really sorry you guys feel that way, and abandoning ship, but I can't do much about that either. Unless someone / many ones are wanting to step up and maintain the android SDK, I'm not sure it's relevant to discuss much more over here. (also this feels more like a bashing than a discussion).

I'll close the discussion here, feel free to reopen on the Android SDK.

**Comment by natario1** [comment]
@flovilmart sorry, but let’s pretend I am an experienced Java developer. I start working on it, make ParseObject parcelable, implement LiveQuery, stop using undocumented, deprecated GCM stuff. Then my PR lies open, just like 95% of what was opened in the last months. What do we do?

I think some words are needed from current maintainers, e.g.
- sorry, we are still alive and will try to merge PRs and guide community efforts
- please fork the library as we have absolutely no time
- please, if someone wants to step up, join our team as a maintainer <- this is not obvious

**Comment by flovilmart** [comment]
> please, if someone wants to step up, join our team as a maintainer

The best way to get that would be to open those PR, start commenting on issues etc...

**Comment by nitrag** [comment]
@natario1, slow down. Let's stay on target.

The point of this thread was not to rant and re-hash what is already known but to get Android developer support in the community.

@flovilmart I understand you are encouraging the community to step up but as mentioned before the PR's just sit there unapproved. Can you ask FB or Android maintainers and to spend a few hours of their time approving the PR that are already out there? Once we get the ball rolling on PR's more people will contribute. Finding a maintainer within a 5 day window here was never likely. Let's focus on breathing life into the SDK first. I'd really hate to fork it, that just get's messy and confusing for new devs.

**Comment by benitech** [comment]
I have been a part of opensource community for many years on various Apache projects and know well how it works.

I am happy to have left parse totally and @flovilmart 's comments make me feel even better about doing so.

Good luck and good riddance.

**Comment by flovilmart** [comment]
@benitech thanks for making me feel wasting my time on helping you instead of someone else.

**Comment by benitech** [comment]
feel free to make yourself feel as self important as you can.

**Comment by MartinHerman** [comment]
Seriously - how the hell did this turn into a rant?

Maybe we could summon @inlined (one of the orig. contributors to the Android SDK)? He has worked on the massive PR that never got accepted - but seems to be working on Firebase now - however he still contributed to the Android repo...

@flovilmart I really thought you were a member of the Parse team... you've done a great job.
@benitech - what the actual f*ck.

To be honest, I won't be jumping ship just yet and I'm willing to contribute to the iOS SDK, as far as my experience will allow.

What would move things along is a Parse Slack channel - anyone know of one?

**Comment by nitrag** [comment]
@benitech STFU. 

@flovilmart Ignore the losers please. You do great work.

**Comment by flovilmart** [comment]
@nitrag as always

There is the gitter open, https://gitter.im/ParsePlatform/Chat

I don't hang out much there but that would be a good start for discussing int

**Comment by benitech** [comment]
you wanna get abusive, then write it in detail. no need for acronyms.

**Comment by flovilmart** [comment]
@benitech your account have been reported.

**Comment by inlined** [comment]
It's fun to be summoned, though I'm sorry it was due to frustration.

For everyone's sake, let's all take a deep breath and be sure we're calm before continuing. As a wise Parser once told me, always try to deescalate. In the meantime, I'm glad to offer some background if it will help:

**FCM**: I was actually the Parse Push developer, not really an Android maintainer. I'm a pretty bad Android dev, so this is better for everyone. The PR I sent out tried to move the Parse Android SDK to GCMv4. I couldn't reveal at the time this was in prep for the public release of FCM. I didn't want the Parse SDK left in the cold when FCM was officially released and I got permission from Google leadership to contribute in that narrow regard.

The PR was rejected for the right reasons. Parse went through pretty long lengths to reverse engineer GCMv3 so the Parse Push API could be implemented without a dependency on GMSCore, which contributes to the DEX limit. Unfortunately GCMv4/FCM is a _much_ thicker client and it would be foolish to reverse engineer. Also, due to a behavior change in multiple senderID registrations from v3 to v4, this PR had to drop Parse's senderID when the developer provided their own. If the developer's account had any trouble there would be no backup. The advice was to wait until Parse.com is fully sunset before endangering the Parse.com experience.

Now that the radically simplified FCM SDK exists & the Parse.com shutdown is sadly here, I think it's definitely time to do some deep cuts in the Android SDK. Almost all of the ParsePush code can be ripped out--from PPNS to the GCMv3 helpers to the weird trampolines we added to reuse BroadcastReceivers/IntentServices to avoid new setup instructions. Instead, just one BroadcastReceiver can be repurposed to listen to the Intent sent by FCM when a new token is found and stuff it into ParseInstallation. Devs who add the FCM dependency will just work (no code necessary) and devs who don't use Parse Push won't lose the DEX space.

I've been burning the midnight oil for a long time now and add can't afford to add this to my plate, but I'd be glad to give someone tips if they want to take a whack at it.

**Parcelable**: I appreciate the praise for Parse's simplicity. To abuse a quote: it takes a lot of complexity to make good simplicity. ParseObject's state management is really complex. Look for "opSetQueue" and you'll start to pull on that thread. `ParseObject.save` causes a recursive save on all dirty children of that object. It's the reason you love Parse's simplicity, but it also means that a ParseObject isn't a simple serializable atomic unit. Tearing the state could be very dangerous to your app. I'm not even sure what should happen if you broadcast a ParseObject to another app--that app could interpret the ParseObject as its own and try to do some weird stuff. It'd likely clog the entire network queue for that app if it ever tried a save.

The real Android stewards were very good at what they did. I'd create a separate request inside the Android SDK repo and tag an owner to get better context here. I _highly_ recommend working out a strategy for Parcelable before doing any coding. The result of the conversation might be that that the intentional decision to not implement Parcelable stands.

**Community**: First and foremost, @flovilmart deserves respect. He is an unpaid contributor working in his area of expertise. He has been so active in the community that even I once thought Parse had hired him after I left. You won't get anywhere treating a gift as an obligation--@flovimart's prior contributions don't require him to give anymore and his skills in ParseServer don't mean he's the right person for any Android love.

The dirty secret about Parse's open source future is that it's at risk because of community abuse. Not a single Parser, past or present, is happy with the shutdown. A lot of good people poured their soul into Parse. The people who stuck around to help the community took a lot of abuse from developers who were hurt & angry about the shutdown. Anyone would have trouble staying moralized when stuck between a parent company that pulled your project and a community that abused you for it.

Here and everywhere else, please remember that open source is a gift and you get the community you create. If you want to contribute, make sure the maintainers are on board with changes before you do them. If you are asking someone to contribute for you, try to make it easy for them to help you. If a repo needs TLC, talk to the owners about why. Here it seems the Android SDK needs an active contributor. Try to find one who is willing and able to do the job. If you know enough to talk about `Parcelable` and outdated dependencies, you might actually fit the bill. None of us really knew what we were doing when we started. You'll just need to accept a slow ramp-up as you learn the design decisions that guided the codebase.

**Comment by natario1** [comment]
Funny to see people bashing at @flovilmart, when all we’d need is just another flovilmart for android :-) respect to you man.

>  If you want to contribute, make sure the maintainers are on board with changes before you do them. If you are asking someone to contribute for you, try to make it easy for them to help you. If a repo needs TLC, talk to the owners about why. 

Thumbs up. There’s a kind of vicious circle to be broken, due to owners somehow being away and contributors not being encouraged to contribute. I think breaking it takes something from both sides.

**Comment by MartinHerman** [comment]
> Not a single Parser, past or present, is happy with the shutdown. A lot of good people poured their soul into Parse. The people who stuck around to help the community took a lot of abuse from developers who were hurt & angry about the shutdown. Anyone would have trouble staying moralized when stuck between a parent company that pulled your project and a community that abused you for it.

What a shame really... @inlined, do you happen to know if someone from the old Parse team would even consider coming back to the Android repo? If not @nitrag where do we go from here? As I've already wrote - I'll be taking a look at the iOS issues, but there is nothing I can do for the Android SDK :/.

**Comment by alexblack** [comment]
I'm also curious, what are some possible next steps then?  Is it that we need someone to ask @nlutsenko for merge permissions on the repo?

**Comment by flovilmart** [comment]
I'm not sure one want to 'give' merge permissions to anyone at random. There is some trust to be established first with external contributors. So the next natural step is that some/many ones start to actively maintain the project, open PR's, help with issue triage, investigation etc... before we can talk about commit access. 

This person should at least demonstrate some knowledge of the AndroidSDK and complete understanding of the parse platform in general. 

I'm happy to discuss this point of view. 

I'M pretty sure that if one or few people start taking this matter in their hands, @grantland and/or @wangmengyan95 will happily leave the keys to the castle to those people. 

As for me, unfortunately, I'm not versed enough with Android to provide a critical eye on the Pull requests, nor have sufficient knowledge of the SDK.

**Comment by alexblack** [comment]
"I'm not sure one want to 'give' merge permissions to anyone at random."

I didn't suggest that. No need to be argumentative.

**Comment by alexblack** [comment]
Here is something concrete that could be discussed, this PR looks (I think) like it could be merged, what would a good next step for it?

https://github.com/ParsePlatform/Parse-SDK-Android/pull/548

**Comment by flovilmart** [comment]
Here I disagree, the justification of the fix seems weak, no test added etc...

**Comment by alexblack** [comment]
Good point. Is this the next step then: close it, until test(s) and (possible more) justification are added?

Is this something the current maintainers should do, or, something we need new maintainers to do?

**Comment by codegefluester** [comment]
Hey everyone, thanks for bringing this up. I flagged this issue internally to the Parse team to discuss it but I can't make any promise about outcomes though.

Just like @flovilmart I do not know enough about Android Development, let alone how the Parse SDK does things in detail to provide any useful help with the Android SDK that would go beyond helping get all the details off folks that report issues to make sure that we have solid repro steps etc.

In general I feel that there is more involved than just maintaining the SDKs itself. The development needs to be driven together with maintainers of Parse Server to make sure that they're both well aligned and that no breaking changes are introduced too often and that older SDKs stay compatible with the Parse Server (not sure how this is handled at the moment).

Some of this can and should most likely be done by using the Parse Evolution process @flovilmart kicked off here https://github.com/parse-server-modules/parse-evolution.

**Comment by nitrag** [comment]
@flovilmart what about this, it's very straightforward.

https://github.com/ParsePlatform/Parse-SDK-Android/pull/506

**Comment by flovilmart** [comment]
Again, I don't have commit access on the Android SDK nor want to take the responsibility that comes with merging code. I already have my hands full, and also lagging behind on many side projects (like the file migration tool).

> The development needs to be driven together with maintainers of Parse Server to make sure that they're both well aligned

I can't agree more with that.

**Comment by alexblack** [comment]
I was hoping we could discuss actual next steps for the Android SDK.

It (appears to me that) the issue is that the repo does not have active maintainers.  So I am wondering (not being an expert on this stuff), if the solution is not to find new maintainers, so that PRs (like the one's mentioned above) could be taken to the next step (whether that be merging, rejecting, etc).

**Comment by nitrag** [comment]
Well, I was asking if you thought the justification seemed weak for that one too.

Ok, let's give this another week for either a community developer to step up or for guidance from Parse team. If nothing happens, I'll fork the repo myself and have it be an Unofficial SDK where PR's get attention.  I don't see any other way to move forward.

**Comment by flovilmart** [comment]
@nitrag it seems that you're willing to maintain a forked SDK, why not maintain the official SDK?

**Comment by nitrag** [comment]
> This person should at least demonstrate some knowledge of the AndroidSDK and complete understanding of the parse platform in general.

- [ ] Knowledge of AndroidSDK
- [x] Knowledge of Parse platform

I'm only just starting to get into Android development. Likewise I'm a Swift developer, not Objective-C. I'd be an amateur maintainer good for handling the low hanging issues. Anything advanced would be over my head and I wouldn't want to be responsible for it breaking someone's app - hence the Unofficial repo.

**Comment by flovilmart** [comment]
ok... but I don't believe the fork is the solution, actually that may end-up making things worst...

**Comment by inlined** [comment]
That second pull request seemed OK. I'm honestly not sure why there was no accept nor comment. The repo does seem a bit active though. @grantland accepted a PR just 5d ago. He's a great Android dev, but he's no longer related to Parse and I'm sure his day job calls.

To help do my part, I [started a discussion](https://github.com/ParsePlatform/Parse-SDK-Android/issues/572) on the Android SDK repo about what to do w/ Push.

**Comment by alexblack** [comment]
hey @inlined I don't see that PR that was accepted 5d ago, latest commit I see on master was Nov last year?

https://github.com/ParsePlatform/Parse-SDK-Android/commits/master

**Comment by inlined** [comment]
Ack You're right. I must have remembered wrong from when I skimmed this morning pre-coffee.

**Comment by MartinHerman** [comment]
Guys have we moved forward on this? The next step should be updating the READMEs so its clear we are looking for maintainers...

**Comment by codegefluester** [comment]
@MartinHerman I raised this to the Parse team and we're discussing the next steps, hang in there.

cc @gfosco

**Comment by WebRence** [comment]
Even I am excited to see next update on [Android Mobile App SDK](http://www.webrence.com/mobile-app-development/) because I am usually doing more work on android apps. :)

**Comment by natario1** [comment]
No news about this, or is there a discussion going on somewhere else?
@codegefluester

**Comment by MartinHerman** [comment]
@inlined @flovilmart @codegefluester  - guys, any news on this?

**Comment by codegefluester** [comment]
@MartinHerman @natario1 Nope, haven't heard anything new so far

**Comment by flovilmart** [comment]
Is any one of you interested in taking over? It first starts with triaging issues.

**Comment by rogerhu** [comment]
@flovilmart I can help =)

**Comment by rogerhu** [comment]
Given the Parse shutdown, the question also behooves what min Android SDK version is needed.  A lot of backwards compatibility choices were made to support older Android versions (https://github.com/ParsePlatform/Parse-SDK-Android/issues/189).  I think the community can be more aggressive about supporting newer Android versions and then receiving help to address backwards compat issues (https://github.com/ParsePlatform/Parse-SDK-Android/issues/231 for instance, HttpUrlConnection should be good enough to go)

**Comment by Jawnnypoo** [comment]
@rogerhu Seems like you could do a great job with contributions. I think part of the problem comes from lack of people with rights to merge PRs, which is part of the reason why the project is slipping. Personally, if I make a PR and it goes unmerged/uncommented on by the maintainers for a number of weeks/months, I am pretty discouraged from making any more contributions. 

Quite a few of the open PRs right now all address the same issues; the Parse Android SDK not being buildable on Android 23+. Accepting one of those would be a great start and would eliminate the fact that everyone who forks the repo and goes to make changes has to go through this same process of first updating the SDK to the latest dependencies. @flovilmart Do you have the ability to add individuals as collaborators/members of the Android SDK repo?

**Comment by flovilmart** [comment]
I can't add contributors to the repo like that, also, this contributor status is not something that is given  but earned. If anyone is wanting to take the lead, establish a vision, etc... I'd be more than happy to help get those access.

Note that so, far, most of the comments on that matter are complaints that no-one is taking over but none have clearly stated their intention to take over. I have neither the time nor the capacity to maintain the android project. My hands are full with my full time job, (yes I don't work for Parse nor Facebook), the maintenance of parse-server, the iOS SDK's, and parse-server-modules organization, and my 3 kids. 

That being said, if anyone wants to move forward taking over, start helping to solve the issues, we'll find someone to review the code, and get it merged from now on. As for past PR's they may not have received any attention for multiple reasons, but that role of maintainer would be to start understanding why.

**Comment by alexblack** [comment]
I'm curious, who is the person(s) who can grant contributor status?

As far as supporting old Android SDKs, I'd still love to see support back to Android 16 (4.1)

**Comment by rogerhu** [comment]
I was the last person to add the major upgrade from OkHttp2 to OkHttp3 in this library so feel somewhat of a personal responsibility to get some of the bugs that I introduced. :) Things like https://github.com/ParsePlatform/Parse-SDK-Android/pull/548 and https://github.com/ParsePlatform/Parse-SDK-Android/pull/506 seem somewhat straightforward to get merged in.  The removal of the legacy Apache HTTP library is also something that seems to make a lot of sense.

The latest OkHttp library also supports web sockets (https://medium.com/square-corner-blog/web-sockets-now-shipping-in-okhttp-3-5-463a9eec82d1#.xlkgirivu) which would also help the project start to achieve parity with LiveQuery support.  I think that would be the next priority to get going.  I'm sure there are people in this thread who would be excited to work on it with help/guidance from Parse contributors.

**Comment by flovilmart** [comment]
@rogerhu yeah we started with @mmimeault the liveQuery android SDK, I believe it makes sense to keep both projects separated (for maintainability) :)

**Comment by nitrag** [comment]
We need to get the ball rolling and I think that involves breathing some life into the SDK by merging existing PR's or rejecting them with comments.

@flovilmart can you speak to the powers at be to spend a few hours over the next two weeks on the existing PR's. Without this I don't think we'll ever move forward.

The we can reach out to some of the "forkers" and get them to include their updates.

Long term, I'm also recruiting some of the parse-server hosting providers to contribute resources to the SDK's. They say that after things stabilize on their end they will move into the maintainer role but that probably won't be for another month or two from now.

@rogerhu If you upgrade to OkHttp3, will Android 16 be supported? I'm with @alexblack and still think our apps should be backwards compatible to at least this level.

**Comment by rogerhu** [comment]
OkHttp3 is already in the Parse Android SDK 1.13.0+.  It was probably the last major commit (8b10c8d8b16283e08fd109cfec890f178a2a2bfa) before this SDK went into hibernation.  
Yes, absolutely, Android 16 should be fine.   Do you see any compat issues in the current SDK version? 

HttpUrlConnection is the primary interface now for the Android network library, and it so happens that OkHttp was backported as the engine that powers HttpUrlConnection in Android 4.4 (API 19) (https://twitter.com/jakewharton/status/482563299511250944?lang=en).   

The Apache HTTP Client that's part of Android and removed after API 23 is largely abandoned by Google (https://android-developers.googleblog.com/2011/09/androids-http-clients.html). But we're talking abandoned since Gingerbread (Android 2.3) :)

**Comment by flovilmart** [comment]
> I'm also recruiting some of the parse-server hosting providers to contribute resources to the SDK's.

That would be nice, but I pretty much gave up on them. They had a full year to move forward, and instead didn't really do anything (with a few exceptions)

**Comment by nitrag** [comment]
@flovilmart I'm not relying on them or saying we should wait for them to move forward. I'm just saying it's **likely** more support will be coming. That's all.

Here's the latest from Sashido.io, received yesterday.

> We really want to start devoting time on Github, but we are still working on implementing features for the mass of users such as backups, SSLs,etc. The bad thing is that these take a lot of time. So up until now we haven't got the time to complete these and focus on anything else. We will do it at some point, we just can't promise a date. The engineers do their best to work as fast as possible on the features we are implementing,but some of them need more time. We'll keep you posted. 

We still need you to motivate the current maintainers so we can get the ball rolling. I've started the Android Nanodegree this week, I'll help where I can but I'm far from qualified at this point.

**Comment by flovilmart** [comment]
AFAIK, the parse.com team was about 20 people full time, 1/3 was devoted to deployments, the rest mostly on SDK's and server code. That gives a rough estimate of 14 full time engineers to maintain the platform and evolve that the same pace it one moved. 

On parse-server, I can quite confidently say that the team is more than capable of handling it, we have about 10 external people with commit access. The parse-server-module org is also quite OK, with many people with commit access.

If we could have at least 2-3 people per client SDK to take over then we could really  start moving the ball faster and forward.

There has been some discussion to ease client side development like leveraging new techs like graphQL. On my side this is something i'm exploring for parse-server (being graphQL compatible). That would alleviate the need of custom SDK's as we'd be able to rely on 3rd party implementations while providing a lightweight modern SDK for push, localDatastore etc... 

In a sense, this idea is motivated by the need to reduce the burden on SDK maintenance, but it starts on the server. (building a full graphQL<-> parse bridge).

I understand this is a 180 degrees turn that won't happen overnight, but I can definitely see it as a future-proof solution, giving you a base implementation of graphQL on the top of the Parse REST.

**Comment by rogerhu** [comment]
I've looked through the majority of the tickets and responded to at least 27 of them (https://github.com/ParsePlatform/Parse-SDK-Android/pulse).  Here is where I think the work needs to go:

1. Fix OkHttp3 upgrade bugs and release a new build ASAP
- If clientKey = null, don't set as a header (https://github.com/ParsePlatform/Parse-SDK-Android/pull/506/files)
- Release fix that deals with ParseFile.save() issues (https://github.com/ParsePlatform/Parse-SDK-Android/pull/542/files
- Confusion about issues with ParseFile limits > 10 MB because of a BinTray caching issue (https://github.com/ParsePlatform/Parse-SDK-Android/issues/491#issuecomment-234337140)

2. Upgrade Parse OkHttp libs 
- Add a Parse hotfix for https://github.com/ParsePlatform/Parse-SDK-Android/pull/542/files
- Upgrade to OkHttp 3.6.0 (https://github.com/square/okhttp/blob/master/CHANGELOG.md)
- Deprecate use of Apache HTTP Client (https://github.com/ParsePlatform/Parse-SDK-Android/pull/542)

3. Resolve some saveInBackground() (https://github.com/ParsePlatform/Parse-SDK-Android/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20saveinbackground) and Parse.getCurrentUser() bugs (https://github.com/ParsePlatform/Parse-SDK-Android/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20currentuser)

4. Figure out a plan for FCM and Parse Push (https://github.com/ParsePlatform/Parse-SDK-Android/issues/572).  Resolve and close GCM co-existing issues (https://github.com/ParsePlatform/Parse-SDK-Android/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20gcm%20

5. Figure out how to support LiveQuery (work in progress, but could benefit from OkHttp 3.6.0 upgrade?)

**Comment by flovilmart** [comment]
That sounds like a plan! @hramos, can you add @rogerhu to the maintainers of that repo, so he can start moving forward? And probably me, just in case?

Thanks @rogerhu!

**Comment by hramos** [comment]
Invited both of you folks.

**Comment by rogerhu** [comment]
Thanks!  We now need help figuring out how to get the Sonatype staging released. :)

**Comment by ly85206559** [comment]
We have use Andorid SDK for half a year,and found pretty much bugs in Android SDK. 
For example, Local cache is not good to use, some times it took much time to find dirty objects.

**Comment by nitrag** [comment]
@ly85206559 We have @rogerhu to represent the community for improvements to the SDK. Please open a Issue with a reproducible error over at the [Android SDK.](https://github.com/ParsePlatform/Parse-SDK-Android/issues)

**Comment by rogerhu** [comment]
FYI I have access now to publish to jcenter but not sonatype.  I am planning to pull the trigger and publish to the former until I can get help pushing to the latter..

**Comment by hramos** [comment]
Access to Sonatype should be granted to you soon @rogerhu

**Comment by rogerhu** [comment]
Thanks!  They granted me it. :)
