### ISSUE TITLE
MongoDB WiredTiger storage system for Parse-Server?

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-server#345]
Simple question if parse-server works well with the new storage engine WiredTiger which provides a newer storage engine that compresses your database data over the standard MMAPv1.

My guess would be parse-server wouldn't care what default storage engine your using ..

**Comment by blackxored** [comment]
I ran into issues with it, although in retrospect I'm not entirely sure since I attempted the migration really really early, where I hit schema bugs and what have you. 
However they explicitly have a requirements on mongo 2.6 up to 3.0. If I had to guess >= 3.0 made wiredTiger the default, so that might be one of the reasons. 
Hopefully we'll get a better answer ;)

**Comment by drew-gross** [comment]
The reason we only supported 2.6 and 3.0 is because they are the ones we use on hosted Parse. My intuition is the same as yours, that WT and/or 3.2 would just work, but we don't want to officially support it until we've tested it thoroughly, and we just haven't had the time for that yet.
