### ISSUE TITLE
[Error]: cannot modify user function () Attempting to update the _User table

### ISSUE THREAD

**Issue by CaseyTeeps** [ParsePlatform/parse-server#360]
Example Using:
`[[PFUser currentUser] setObject:[NSNumber numberWithBool:NO] forKey:@"inOffice"]; 
[[PFUser currentUser] saveInBackground];`

Log output:
` [Error]: cannot modify user function () { return this.data.objectId || this.query.objectId; } (Code: 206, Version: 1.12.0)`

iOS obj-c
Hosting the current parse-server-example on mongolab/heroku
Parse-server 2.0.7

**Comment by gfosco** [comment]
This error *message* will be fixed in 2.0.8, a change landed in #254.  But what the error intends to say is that you don't have permission to save the user, as if you have been logged out / your session is no longer valid.  This could point to some other issue, but you'd need to investigate further.
