### ISSUE TITLE
Client push unavailable

### ISSUE THREAD

**Issue by rogerhu** [ParsePlatform/parse-server#396]
After https://github.com/ParsePlatform/parse-server/pull/311 got merged I started testing it again.  I started seeing 
"Master key is invalid, you should only use master key to send push'" on Parse push registrations.

I don't believe the Android SDK has the ability to send a master key ( (https://www.parse.com/questions/using-master-key-with-android). so I had to disable this [line](https://github.com/ParsePlatform/parse-server/blob/master/src/Controllers/PushController.js#L17) to get push notifications registered.

Is it possible to remove this validation until the Android/iOS SDK's enable this possibility?

@wangmengyan95

**Comment by rogerhu** [comment]
After disabling it, I was able to validate user and channel pushes though!

**Comment by wangmengyan95** [comment]
Hi @rogerhu, as we said in wiki, we do not officially support client push yet. The main reason is related to security. Since you will distribute the app with your clientKey, malicious users can use that to send push notifications to your app users if you enable client push. For Parse.com, we have the dashboard to remind you and allow you to change this setting. It is disabled by default. For open parse server, we simply disable the client push at the beginning. Compare to client push, we always recommend developers to use cloud functions to send push notifications.
I will send a PR to allow you to enable client push when you initialize parse server later. Removing the checking does not have an effect on the push functionality, just be aware of the security issue I mention to you.

**Comment by rogerhu** [comment]
Yep makes sense thanks!

**Comment by rogerhu** [comment]
Thanks again for the input...the security concerns are duly noted.  

Wondering if there's a PR that you have?  We have a bunch of group projects that are going to be spinning up hosted Parse so curious to see if we'll be able to get it so it can be supported.

Thanks!

**Comment by edwardyue** [comment]
I encountered the same too 
[Error]: Master key is invalid, you should only use master key to send push (Code: 115, Version: 1.12.0)

Could you please send us the solution?

**Comment by gfosco** [comment]
Are you trying to **send** a push from Android?  We are not going to support that, you should call a cloud function and send the push from there.

If you're having a problem just registering for push, not sending, please re-open.

**Comment by gowridev** [comment]
How to send client push notifications for multiple users using cloud code? I am able push to single user with help of this [link](http://blog.parse.com/learn/engineering/the-dangerous-world-of-client-push/) (I am unable to come up with Query for multiple users?)
