### ISSUE TITLE
Integrating parse server with react native

### ISSUE THREAD

**Issue by asContagious** [ParsePlatform/parse-server#461]
Has anyone successfully integrated a self-hosted parse server with React Native? I'm curious how one would do this.

**Comment by mikepaggi** [comment]
It's not any different then doing it with Parse.com.  You would use the JavaScript SDK to connect with your Parse Server.  I do this and you just need to specify your API location with the newly updated JavaScript SDK to support Parse Server.

**Comment by drew-gross** [comment]
Thanks for the help @mikepaggi!

**Comment by temitope** [comment]
@asContagious @mikepaggi have you guys ran into any issues with react native and parse since using them together? I really love the channel based push of Parse amongst other things, but thinking about using Firebase to avoid the mongodb server cost if possible and also because of the maintenance...thoughts/ideas/advice? cheers

**Comment by Warmachine13** [comment]
same problem
