### ISSUE TITLE
Comparison between pointer and [PFUser currentUser]

### ISSUE THREAD

**Issue by refre5h** [ParsePlatform/parse-server#521]
`user`, a pointer, and `[PFUser currentUser]` are referring to the same user. With hosted parse, `[user isEqualTo:[PFUser currentUser]]` returns `true`, but with parse-server it returns `false`.

A workaround is `[user.objectId isEqualToString:[PFUser currentUser].objectId]`, but that requires a huge amount of changes in our client code as we did most comparisons like `[user isEqualTo:[PFUser currentUser]]`.

Also may be related: when the client is connected with hosted parse, `user`, the pointer, and `[PFUser currentUser]` seem to be regarded the same and data inside are always available. But when connected with parse-server, those two are different, so I can not get any data from the pointer object.

Is this a bug? If not, any advice please?

**Comment by nlutsenko** [comment]
Hey @refre5h, few questions here to help debug the issue:
- `isEqualTo:` is not a built-in default method - any chance you can expand on the implementation there
- Are you using Local Datastore on the client?
- If yes - comparing by identity (aka pointer comparison) will be the best and fastest solution, since we have a guarantee on a single instance per className+objectId pair.
- Comparing users by `objectId` is actually the intended flow and any other comparisons were not guaranteed to work.

On the top of all of this, if you could open the issue on the iOS SDK repo - that would be ideal, since it's more related to the client at this point.

**Comment by refre5h** [comment]
Issue opened in iOS SDK repo, closing this one.
