### ISSUE TITLE
Is Parse Server easily manageable?

### ISSUE THREAD

**Issue by rihadavid** [ParsePlatform/parse-server#55]
Hi, we are developing Xamarin app using Parse. I know very little about managing servers and I'd like to decide wheter it's a good idea to go this way. I'd like to make a few things clear to me.

1. Is this great opportunity to get own backend solution for free or is there some kind of a risk to base our backend on Parse Server? 
3. Is it safe for now to use Parse Sever deployed on AWS without backend developers in our team, in production? Will it be stable without the need to manage it? Or can it happen that Parse Server will crash and we will not able to fix it in reasonable time? Were parse.com downtimes caused by something that should not happen to single instance or is this a risk?
5. Let's say one day Parse Server or Parse Xamarin SDK becomes outdated and the community will not thrive (I hope this will never happen but let's say it will) - if we hire team of backend developers, will it be easy for them to continue with the development on their own and keep the server running well? Or is the Parse Server too complicated for just a few backend developers to handle all about it? Will they be able to handle our instance of Parse Server just the same as they would handle their self-build backend? Or would it be better to get team of backend developers now and build our own server solution from scratch?

Thanks for any kinds of answers :)

**Comment by adampietrasiak** [comment]
+1

**Comment by NglSR** [comment]
+1

**Comment by lacker** [comment]
Well, it won't be totally free, you'll have to pay your infrastructure provider, AWS or whoever you pick.

Parse Server may crash. Like any other server-side open source framework, it is not infinitely resilient to what you do to it. In particular, you will need to decide in some way how much resources to allocate to your app - like the # of dynos on Heroku, size of your database, memory on your VM, something like that. And if you use more resources than you allocated, the app will crash. You should either be confident that your app will have super low usage, or you should acquire the basic skills needed to operate a server.

You sound competent so my advice would be to learn the very basics of operating a server. Just like, ok let's say it crashes. What do you do now? Something like, look at some logs, figure out why it crashed, fix the problem. It is not rocket science and these skills will serve you well. Run through this before you go into production. If you have a server but it's not crashing, you can try putting more load on it and adding weird pointless database queries until it crashes.

Overall if you want the easiest thing possible that will still be fairly scalable if you add a big eng team later I would suggest starting off with Heroku rather than AWS. This applies whether you use Parse Server or do not use Parse Server. And you can go from Heroku -> AWS later without too much pain if you want.

**Comment by rihadavid** [comment]
Thanks for advice Kevin!

It sounds that I could manage it in the start, but as soon as I put the app in production, I would be anxious that the app will crash while I sleep or something like that.

I just realized there are some companies ([lot of them](https://aws.amazon.com/partners/msp/)) that should be able to deploy our Parse Server and maintain all about it - keep it running, fix crashes, keep the AWS costs as low as possible, set up all the environment in AWS etc.

I guess that something similar is possible with Heroku too.

Do you think this is good solution? Do you know about some managed AWS/Heroku provider who is free/cheap when the app is not in production yet?

Thanks.

**Comment by christianmarth** [comment]
Hi,

You can manage this using a micro instance on AWS on your free tier, if using heroku you can also use the hobby tier or even using a small server on Digital Ocean for very cheap. It's possible for you to start off with Heroku then move to Digital Ocean or AWS

Once the parse server is set up there's not much maintenance required and as it's using standard open source technologies such as node.js and mongodb it's not difficult to find a partner that can assist to manage it moving forward.

[My Company](http://appfibre.com)] can provide this service at a very reasonable if required. (Forgive the shameless plug)
