### ISSUE TITLE
Sendgrid Cloud Code Module

### ISSUE THREAD

**Issue by dcdspace** [ParsePlatform/parse-server#554]
Since Cloud Code doesn't support modules anymore, how can I still use an email service like Sendgrid to send transactional email? Right now I am using its cloud code module, but that does not work in Parse Server. Thanks for the help.

**Comment by flovilmart** [comment]
https://github.com/flovilmart/parse-sendgrid

**Comment by zeluspudding** [comment]
Dylan, 
Were you ever able to solve your sendgrid (cloud module not supported) problem? I'm currently managing my cloud code transition and am also feeling a little lost.

**Comment by dcdspace** [comment]
Yes, I was. 

1. In your `package.json` file, add the dependency to the Sendgrid npm module:
   `"sendgrid": "^1.9.2"`

2. Re-write your cloud code function to follow the new Sendgrid module syntax (slightly different than old unsupported Cloud Code module) https://github.com/sendgrid/sendgrid-nodejs https://www.npmjs.com/package/sendgrid

Note that instead of initializing Sendgrid with your username and password, I recommend you make an API key from the dashboard and use that instead.

Should work from there, lmk how it goes.

**Comment by zeluspudding** [comment]
Thank you @dcdspace. I've since been able to require sendgrid in my projects although that didn't seem to help for sending password reset messages. I see you ran into a similar problem in issue 275. I've setup the parse-server-sendgrid-adapter to basic success - that is, I can get sendgrid to send reset passwords but the reset link doesn't work and I get "undefined" fields as shown below:

![sendgridtest1](https://cloud.githubusercontent.com/assets/8431341/13852277/5950fcf6-ec2f-11e5-821b-895ca727551f.PNG)

Have you been able to successfully send password resets? #275 #971

**Comment by dcdspace** [comment]
No @zeluspudding I've only been using Sendgrid with custom templates for transactional email such as for welcome messages and in addition to push notifications for friend requests. I would however love to use my custom templates for a password reset/email verification email, so it would be great if we could directly access the reset link, and be allowed to customize the reset page. 

I'm also not `using the parse-server-sendgrid-adapter`, but I assume it works the same as the `sendgrid` npm module I'm using? Also where did you find the documentation on how to use the password reset? Thanks.

**Comment by zeluspudding** [comment]
@dcdspace, It appears "adapter" is synonymous with "wrapper" as `parse-server-sendgrid-adapter`'s only dependency is `sendgrid`. @carmenlau is its author and likely has more useful info for the both of us for getting it setup correctly (I just included it in my express server initialization as [shown here](https://www.npmjs.com/package/parse-server-sendgrid-adapter) and got the gnarled output attached above. Any advice to get us setup with working reset password links @carmenlau? Should we continue this conversation at #971?

**Comment by zeluspudding** [comment]
After a little more poking around I've come across this - gaze your eyes upon the following:
![passwordreset](https://cloud.githubusercontent.com/assets/8431341/13896783/89dba090-ed67-11e5-9681-ccb7e53bd428.png)
So the fields pointed out by the number 1 in Pane A are indeed set by the appName argument when initializing ParseServer in the [index.js](https://github.com/ParsePlatform/parse-server/blob/d5931f70b52f864b635c42332ced856e16f8ff40/src/index.js). If you take a look at that source you can see that appName is the third argument to the `ParseServer` function declaration. Down at the bottom of the argument list are `emailAdapter`, `publicServerURL` , and `customPages`. In order to get password reset emails sent via SendGrid you'll have to set `emailAdapter: SendGridAdapter` as [shown here](https://www.npmjs.com/package/parse-server-sendgrid-adapter). Now the portion of the reset URL denoted by the number 2 comes from setting `publicServerURL`. Following the reset URL takes me to Pane B, then entering my information takes me to Pane C without any sort of confirmation email. Unfortunately, when I try to use my reset password in my client, the client refuses to accept the *changed* password - I imagine it's not really being set. So here are my questions @carmenlau (or anyone): 1) Do you have any idea why password reset isn't actually resetting passwords? Do you know how I can get rid of the supposed image in the reset email (identified by the orange rectangle)? or better yet 3) can you share how one is supposed to configure custom email templates using the `customPages` `invalidLink`, `verifyEmailSuccess`, `choosePassword`, and `passwordResetSuccess` arguments? Any help would be most appreciated.

**Comment by trana-ramius** [comment]
Hey guys

I have followed the digital oceans guideline to migrate my application from this link : 
https://www.digitalocean.com/community/tutorials/how-to-migrate-a-parse-app-to-parse-server-on-ubuntu-14-04

now my application uses sendgrid to send very basic text emails. I have tested my cloud code without sendgrid and it works fine. 

For my cloud code file it looks something like this : 
![documents_ _parse_pacecourier____ _ssh_root_159_203_35_195_ _242x42](https://cloud.githubusercontent.com/assets/17007876/15186664/e38a20d4-176b-11e6-8882-9c04d4678c0d.png)

now whenever I try to run this sendMail function through postman I get an internal server error : 
<img width="965" alt="postman" src="https://cloud.githubusercontent.com/assets/17007876/15186728/29a5beac-176c-11e6-9287-6e01450b82df.png">

If I click the send button multiple times I sometimes get a 502 Bad Gateway error : 
<img width="959" alt="postman_and_sendgrid_cloud_code_module_ _issue__554_ _parseplatform_parse-server_and_new_tab" src="https://cloud.githubusercontent.com/assets/17007876/15187076/b287bfc6-176d-11e6-8517-8062c3b42c4e.png">


Now I figured that its the sendgrid that is throwing this error so I tried to install sendgrid on my droplet. 

I logged in as parse user 

`sudo su parse`

and created a package.json and added the following to it 

`
{
  "dependencies": {
    "sendgrid": "2.0.0"
  }
}
`

i still get the same error message. I tried to install sendgripd globally as root on the droplet as well but it did not help my cloud code run 

`
npm install -g sendgrid
`

I have looked around the internet and haven't found anything as close as this thread to my problem so if any of you guys know how I can fix this I will be greateful as this is the only step left for my application migration.

Cheers,
Tanzeel

**Comment by tanzeelrana** [comment]
Hey guys

I have followed the digital oceans guideline to migrate my application from this link : 
https://www.digitalocean.com/community/tutorials/how-to-migrate-a-parse-app-to-parse-server-on-ubuntu-14-04

now my application uses sendgrid to send very basic text emails. I have tested my cloud code without sendgrid and it works fine. 

For my cloud code file it looks something like this : 
![documents_ _parse_pacecourier____ _ssh_root_159_203_35_195_ _242x42](https://cloud.githubusercontent.com/assets/17007876/15186664/e38a20d4-176b-11e6-8882-9c04d4678c0d.png)

now whenever I try to run this sendMail function through postman I get an internal server error : 
<img width="965" alt="postman" src="https://cloud.githubusercontent.com/assets/17007876/15186728/29a5beac-176c-11e6-9287-6e01450b82df.png">

If I click the send button multiple times I sometimes get a 502 Bad Gateway error : 
<img width="959" alt="postman_and_sendgrid_cloud_code_module_ _issue__554_ _parseplatform_parse-server_and_new_tab" src="https://cloud.githubusercontent.com/assets/17007876/15187076/b287bfc6-176d-11e6-8517-8062c3b42c4e.png">


Now I figured that its the sendgrid that is throwing this error so I tried to install sendgrid on my droplet. 

I logged in as parse user 

`sudo su parse`

and created a package.json and added the following to it 

`
{
  "dependencies": {
    "sendgrid": "2.0.0"
  }
}
`

i still get the same error message. I tried to install sendgripd globally as root on the droplet as well but it did not help my cloud code run 

`
npm install -g sendgrid
`

I have looked around the internet and haven't found anything as close as this thread to my problem so if any of you guys know how I can fix this I will be greateful as this is the only step left for my application migration.

Cheers,
Tanzeel

**Comment by drew-gross** [comment]
Can you enable verbose logging in your server, trigger the error, and post a new issue with the output?

**Comment by tanzeelrana** [comment]
I'm sorry but Im not sure where I can find the log file. 

I have a file ecosystem.json which has parse-wrapper information. Is that the file where I should add VERBOSE = 1 ? 

I did a parse-server command in my droplet command-line saw this in the output :
<img width="604" alt="documents_ _root_pacecourier____ _ssh_root_159_203_35_195_ _226x52" src="https://cloud.githubusercontent.com/assets/2520028/15202624/0426dea0-17ca-11e6-8fa2-d2b0844c5f5c.png">

So I went to my ecosystem.json file and edited it and now it loks something like this (did I set the verbose correctly ? or do I have to set it like VERBOSE=1 and what about the quotes ): 

<img width="761" alt="documents_ _root_pacecourier___home_parse_ _ssh_root_159_203_35_195_ _226x52" src="https://cloud.githubusercontent.com/assets/2520028/15202640/3b3e76be-17ca-11e6-942b-76d2a10caa2f.png">

I ran the following command 

`pm2 restart ecosystem.json`

and I guess it restarted my parse-wrapper 

<img width="654" alt="documents_ _parse_pacecourier____ _ssh_root_159_203_35_195_ _226x52" src="https://cloud.githubusercontent.com/assets/2520028/15202705/b313ab28-17ca-11e6-9620-185e8cc32340.png">

I can not find the log files for the parse-server on my droplet. Do you know the exact location for the log file ? I tried to look around and found nginx log files under /var/log/nginx/error.log. Since I am using nginx according to Digital Ocean's tutorial, I thought that might also help. This is what I saw in its error logs :

> 2016/05/11 11:34:29 [error] 18128#0: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 24.37.6.210, server: test.pacecouriers.com, request: "POST /parse/functions/sendMail HTTP/1.1", upstream: "http://127.0.0.1:1337/parse/functions/sendMail", host: "test.pacecouriers.com"

Thanks 😄

**Comment by tanzeelrana** [comment]
So I looked up at pm2 and to see real-time logs the command is 

`pm2 logs`

at first when I ran the command I saw some errors, maybe they were there from before : 

<img width="1080" alt="documents_ _parse_pacecourier____ _ssh_root_159_203_35_195_ _226x64" src="https://cloud.githubusercontent.com/assets/2520028/15214120/42f855ce-1819-11e6-99a1-0e6393e13c08.png">

Then I tried the hello cloud function from postman app to test for its output in pm2 logs and I got  the following  : 

<img width="1139" alt="documents_ _parse_pacecourier____ _ssh_root_159_203_35_195_ _226x64" src="https://cloud.githubusercontent.com/assets/2520028/15214174/8de77272-1819-11e6-9666-e0073f3eb561.png">

Next I try to run my sendMail sendgrid function and I find out the the api-key I had used in my sendgrid function was throwing an error 
`ReferenceError: XXXXXXXXXXXX is not defined`

<img width="1119" alt="documents_ _parse_pacecourier____ _ssh_root_159_203_35_195_ _226x64" src="https://cloud.githubusercontent.com/assets/2520028/15214365/8acc3108-181a-11e6-942a-0448f097e62c.png">

So I went back to my cloud code and used quotes around my api-key parameter and passed it as a string in my send grid initialize function. Then I retry and get 

`[Error: The provided authorization grant is invalid, expired, or revoked]`

<img width="1114" alt="documents_ _parse_pacecourier____ _ssh_root_159_203_35_195_ _226x64_and_postman" src="https://cloud.githubusercontent.com/assets/2520028/15214987/24bacaba-181e-11e6-9a13-e671ebe56774.png">

So I went back to my sendgrid account and made sure that the api-key I was using was the correct one and it seemed to be just fine. I tested again and got the same error again so I decided to generate a new api-key just in case.

So I realize that I was not using the api-key but instead API KEY ID : 

<img width="1021" alt="sendgrid_" src="https://cloud.githubusercontent.com/assets/2520028/15215724/ee4fcf12-1821-11e6-8863-2dc3d356e41f.png">

When we create a new api-key on sendgrid they give us the actual api key once and they ask us to store it in some secure place : 

`We can only display the key above one time. Please store it somewhere safe because as soon as you navigate away from this page, we will not be able to retrieve or restore this generated token.`

<img width="1240" alt="sendgrid_ _and_abubakar" src="https://cloud.githubusercontent.com/assets/2520028/15215782/3dd4a8a0-1822-11e6-88dd-05cad51972ab.png">

So after I used an actual api-key I was able to send emails 😃 

But one small issue still remains and I am not sure if its because of postman that I am using to run cloud code or something in the parse server or nginx that is still returning me with a 502 Bad Gateway as a response 

<img width="948" alt="postman" src="https://cloud.githubusercontent.com/assets/2520028/15215913/d472a226-1822-11e6-8244-294ebd9ef479.png">

But when I look at the logs for my parse server I do see a 

`parse-wrapper-0 { message: 'success' }`

![documents_ _parse_pacecourier___root_ _ssh_root_159_203_35_195_ _179x47](https://cloud.githubusercontent.com/assets/2520028/15216157/f5356056-1823-11e6-9eca-fea8645bb226.png)

but it never gets back to me in my postman and instead i am getting a 502 error not sure why

Thanks for helping me debug

**Comment by drew-gross** [comment]
This is expected. Also, now that you've posted your API keys, you should rotate them, or anyone can look at this page and send emails as your account.

**Comment by tanzeelrana** [comment]
Oh, my bad. Totally missed it. thanks :)
