### ISSUE TITLE
Parse Server Limitations

### ISSUE THREAD

**Issue by camdagr8** [ParsePlatform/parse-server#686]
This isn't an issue as much as it's a question: 

With hosting your own instance of Parse Server, are the limitations [here](https://parse.com/docs/js/guide#performance-limits-and-other-considerations) still in effect?

**Comment by drew-gross** [comment]
Some of them are (due to being limitations of the underlying MongoDB) and some of them aren't. We don't have a complete guide on limitations yet, but in general you can expect that object size and query related limitations are still there, and Cloud Code related limits are not. Also, by having full access to the DB, you can build your own indexes, which means you can change some of these limits if you put in some effort.

**Comment by csechuan** [comment]
How parse-server manages ParseUser object? e.g. I store a ParseUser around 400 bytes. Let's say I have 40k (hitting 16mb - mongo limit) users signup. On 40001 signup, what happen?
