### ISSUE TITLE
Graphql support

### ISSUE THREAD

**Issue by harisvsulaiman** [ParsePlatform/parse-server#72]
Can the parse server integrate with graphql ? If so multiple dbs can be supported and we can turn this into a huge platform.

**Comment by lacker** [comment]
I think it is logically possible to implement this feature. It seems like a difficult task on par with supporting SQL in lieu of MongoDB. I don't expect Parse folks to work on this but if someone wants to see if it works I would be down. It also might make sense more as a separate repo / addon because I could imagine people not wanting graphql access if they weren't using it, because it might confuse their security model.
