### ISSUE TITLE
parse-dashboard doesn't show any data in parse-server

### ISSUE THREAD

**Issue by okaris** [ParsePlatform/parse-server#855]
#### Environment Setup
parse-server-example running on Heroku
parse-dashboard running on localhost
database running on mLab

#### Steps to reproduce
When I connect to api.parse.com from the dashboard I can see everything. When I connect to my parse-server on Heroku I can only see Class names in the left pane with no counts and no objects inside. JavaScript console shows Error 500. Below is a sample CURL

#### Logs/Trace
ApplicationId and MasterKey is hidden.

curl 'https://coralline.herokuapp.com/classes/_User' -H 'Origin: http://localhost:4040' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8,tr;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36' -H 'Content-Type: text/plain' -H 'Accept: */*' -H 'Referer: http://localhost:4040/apps/Coralline/browser/_User' -H 'Connection: keep-alive' --data-binary '{"where":{},"limit":200,"order":"-createdAt,-createdAt","_method":"GET","_ApplicationId":"application-id","_ClientVersion":"js1.6.14","_MasterKey":"masterkey","_InstallationId":"290164bf-60f5-9499-d8cf-7a38c3b10344"}' --compressed

**Comment by okaris** [comment]
Debugging further showed parse-server throwing:

`Uncaught internal server error. [Error: double colon in host identifier] Error: double colon in host identifier`

The problem was with the node-mongo-native package. There is a commit to fix the broken code in the repo but it hasn't been published as a version yet. 

https://github.com/mongodb/node-mongodb-native/commit/7859a38b659d81c4dd0ee888f6dcd5c9f8111382

So I guess we need to wait for the author to release a new version with the fixed code.

**Comment by Krajiyah** [comment]
I have same setup....but slightly different issue.... please help

I freshly pulled from this repository for Parse Dashboard and my parse-server module works on heroku...i've been using it with my apps, but I wanted to install the parse dashboard too as a seperate heroku app. Before even trying to push to heroku I get issues locally:

My config file for the parse dashboard has the server url in this format: 
http://herokuappname.herokuapp.com/parse

When I check console errors in chrome on the Parse Dashboard it says: "Server not reachable: server version too low" also says in console that it couldnt find the serverInfo page on my parse-server.

![asd](https://cloud.githubusercontent.com/assets/10042218/13551406/8bb7686a-e2ed-11e5-8260-a86c66dfaebc.png)

Can someone please tell me what im doing wrong? Not sure if server version is too low, since I took the parse-server from github.

**Comment by Krajiyah** [comment]
sorry issue was having version 2.1.3 instead of 2.1.4

**Comment by gfosco** [comment]
Interesting bug there on the native driver, but why is it being triggered in this scenario?  So far no one else has reported experiencing this, and we've been playing with the dashboard on various deployments.

From the curl example, you're missing the parse mount, the url should be `/parse/classes/_User`

I'm going to preemptively close this, but it can be re-opened if you have more details.  Thanks.

**Comment by okaris** [comment]
Hi @gfosco. I am using parse at "/" defined with a global variable on Heroku. And I am using the mongo connection string supplied by the mongoLab. Since it has the semi-column for distinguishing username and password and also the port number and since the driver has the typo I have mentioned the connection to my db doesn't work. 

However I know this is not about you guys, I just wanted to open an issue here so anyone else having a similar 500 error issue could check and see if they have the same problem.

Keep up the good work!

**Comment by nsarafa** [comment]
I'm running into the same issue via a very similar setup. @okaris did you happen to find a solution to this?
