### ISSUE TITLE
Question: Are the parse limits lifted when hosting your own MongoDB

### ISSUE THREAD

**Issue by TylerBrock** [ParsePlatform/parse-server#917]
Before moving completely off of parse, but when MongoDB is hosted externally, are the usual Parse service limits in place?

For example the limits on counts, requests/sec, etc...?

**Comment by flovilmart** [comment]
There are no limits in place in parse-server.

**Comment by TylerBrock** [comment]
Right, of course, but I'm wondering about the intermediate stage. When you still hit api.parse.com but host your own MongoDB.

**Comment by mtrezza** [comment]
@TylerBrock The limit of API requests per second according to your current Parse.com plan seems to be still in place when you migrate your DB to your own DB. As long as you keep using the Parse hosted API. You can see when you hit the limit in the dashboard and requests are not served.

**Comment by taufiq-husain** [comment]
How about the limits of queries? Usually parse limited queries of upto 1000 entries. Is this lifted in the open-source Parse server?

**Comment by mtrezza** [comment]
@taufiq-husain Yes, the limit restriction for query results of 1k objects exists. You can retrieve more objects through paging `query.skip = 1000`.

I assume the limitations are due to the original intention of Parse being a **mobile** BaaS. For mobile application it makes sense to return a limited number of results to the client due to cellular network and mobile device resource limitations. The processing and filtering of data is supposed to happen server-side as much as possible, the client should have as little as possible and as much as necessary a) data to work with and b) data processing tasks. Depending on your use case maybe you can shift some logic to cloud code.

**Comment by otmezger** [comment]
@mtrezza will have the same limitations as well... In fact, parse.com had a limitation of 1000 elements per query and a max skip of 10000 if I'm not wrong, so that you could only get around 10.000 elements (in cloud code too). I hoped this will go away in self hosted parse-server.

**Comment by virtualtoy** [comment]
This is weird. [This](https://github.com/ParsePlatform/parse-server/issues/25) claims that self hosted parse-server doesn't apply limits. Just checked parse-server v.2.2.6 and query returned all 7.7k records

**Comment by mtrezza** [comment]
@virtualtoy Thanks for pointing this out. My statement back then was based on an actual test query. Did you set the limit parameter to >= 7.7k or not set it at all to fetch the 7.7k records?

**Comment by virtualtoy** [comment]
@mtrezza I set to 10000. By default it fetches 100 only

**Comment by adambarghouthi** [comment]
@virtualtoy where did you set it to 10000, because my default is 100 also

**Comment by TylerBrock** [comment]
Use the `limit()` method on a Parse Query object.

**Comment by adambarghouthi** [comment]
oh straight in the code, thanks @TylerBrock !

**Comment by finetype** [comment]
is this possible through the REST api?

**Comment by flovilmart** [comment]
Yes, with the limit parameter
