### ISSUE TITLE
"schema mismatch for _Session.expiresAt; expected date but got string" on version 2.0.3

### ISSUE THREAD

**Issue by jimok82** [ParsePlatform/parse-server#94]
This seems to have been mentioned in issue #32 and was supposed to be fixed, however I am still getting this error. This is not on a migrated database, but rather a newly created one by the "parse-server-example" scripts:
 
When trying to login, I am now getting the following error:

Body : {
     "code": 111,
     "error": "schema mismatch for _Session.expiresAt; expected date but got string"
 }

I am currently on version 2.0.3

**Comment by rebelchris** [comment]
You should update the mongod table for _SESSION search for Session and change expiresAt from date to string ;)


On the other hand:
I did change to 2.0.3 and changed expiresAt from date to string

It seems to work, but the js sdk gives me the following error:
Uncaught Error: Tried to encode an unsaved file.

File parse-1.6.7.min.js:9164
I'm guessing it has something to do with this issue? since it was working before..

**Comment by stevenmick** [comment]
I'm on a migrated database & get the same error on sign-in as well.

**Comment by gfosco** [comment]
@rebelchris You should be using at least 1.6.12, which may fix your file issue, but the expiresAt date/string thing is a legit issue that we'll fix.

**Comment by rebelchris** [comment]
@gfosco Actually also in Parse JavaScript SDK v1.6.14 not working ;)

**Comment by yeahio-com** [comment]
I am getting this issue on Android when logging also. Please fix.

**Comment by jimok82** [comment]
@rebelchris Changing the schema by hand fixes the problem, but the problem is that every new install of parse-server with a new DB schema generates a bad schema. This is something that I am sure the developers agree should work out of the box, which is why I reported it :)

**Comment by gfosco** [comment]
The date issue here should be corrected in #147.  

@rebelchris follow along with #136 for the Files issue.

Thanks. :+1:
