### ISSUE TITLE
Geolocation Rest always returns same result

### ISSUE THREAD

**Issue by ldmtam** [ParsePlatform/parse-server#999]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace

I'm using geolocation feature provided from parse server. But parse server always returns the same result array including every location object although i have used the $nearSphere and $maxDistanceInMiles. Please help me out. Thanks in advance.

**Comment by flovilmart** [comment]
Can you post the request you'r doing?

**Comment by ldmtam** [comment]
Assume i have a class with 5 geo elements like this: 
![1](https://cloud.githubusercontent.com/assets/8778071/13726870/5e1d3ee6-e90c-11e5-9a58-b07e9e9b45cf.png)

And i want to get 3 objects that are nearest the longitude and latitude coordinate that i have included in the query and with max distance is 1 miles 
![2](https://cloud.githubusercontent.com/assets/8778071/13726874/8d8dddde-e90c-11e5-94a6-6f8b99fd348c.png)

But the result array always return all of my geolocation objects
![3](https://cloud.githubusercontent.com/assets/8778071/13726878/e7cf7d52-e90c-11e5-9356-bf7f9f09d0e4.png)
![4](https://cloud.githubusercontent.com/assets/8778071/13726879/e8a2824c-e90c-11e5-9566-bc21809c0193.png)

Please help me. Thanks!

**Comment by tahoecoop** [comment]
I have this issue as well, thanks!

**Comment by ldmtam** [comment]
Can anyone help me?

**Comment by drew-gross** [comment]
We have lots of tests that cover Geo Queries, so the information you've provided so far is not enough for us to help you. The best thing you would be able to do is create a reproducible failing test case that demonstrates the issue.

**Comment by msniff16** [comment]
Haven't had time to write a test case, but I have investigated this issue and can confirm that it occurs when using an $or query that is composed of two queries with separate "geoPoint" objects. When I do the same query with the usual parse server (api.parse.com) it does not fail. When I use my new parse-server with an $or query that is composed of one internal query with a geoPoint (nearSphere) object it works. Adding the second query with geoPoint makes it fail. Again, doing the $or with both geoPoint queries inside the $or works when using api.parse.com and not when using parse-server.

**Comment by hramos** [comment]
We are closing this issue due to a lack of sufficient information. 

Please refer to [this issue](https://github.com/ParsePlatform/parse-server/issues/1271) for an example of a great bug report.

You may use [Server Fault](https://serverfault.com/tags/parse) for questions about managing Parse Server.

For code-level and/or implementation-related questions or technical support, please refer to [Stack Overflow](http://stackoverflow.com/questions/tagged/parse.com).

**Comment by msniff16** [comment]
If I find more time to write up a test case, I will in the future. Wanted to make the community aware that this is a likely issue that has not been addressed.

**Comment by javaboyjunior** [comment]
Confused as to why this doesn't have enough information - the exact steps to reproduce are in the original bug report. Create a class with a geopoint column, add some data, query the class with a $nearSphere query with a limit and a distance and you *always* get back all results. I also have this issue. There's even screen shots...

**Comment by flovilmart** [comment]
@javaboyjunior We have tests covering this feature, https://github.com/parse-community/parse-server/blob/master/spec/ParseGeoPoint.spec.js#L187 . I'm not sure why you experience such issue.

**Comment by javaboyjunior** [comment]
@flovilmart This was very helpful - thank you for the response. For those facing the same problem as myself and others on this thread, the issue was that we were storing the lat and lng components of a geopoint as strings. It isn't obvious from the console as they look like numbers but when I ran a query, latitude and longitude values were in quotes. I edited the values manually in the console which converted them to numbers and distance queries started working. Hopefully this information helps someone as it was tricky to track down.

@flovimart quick question if you don't mind. Now we have this working, we have discovered that 'limit' doesn't work. Shall I open a new ticket for that?

**Comment by flovilmart** [comment]
@javaboyjunior I should probably not allow strings or convert the strings to numbers for geopoints. We miss that validation somewhere.

For the limit, I'm curious, if you can provide the full logs as well with the newly opened issue that would be helpful!

**Comment by javaboyjunior** [comment]
@flovilmart I will get on that - thanks very much for your help!
